### ISSUE TITLE
Git pre-push hook fires but console output not reported

### ISSUE THREAD

**Issue by begin-again** [atom/github#2028] opened 2019-03-25 16:39 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

I renamed my profile as described in the debugging guide. There are no packages installed.

### Description

Atom does not report the standard output when a `pre-push` git hook prevents a push.

### Steps to Reproduce

1. cd to git repository
1. run `yarn install` to get dependencies and to also configure hooks `git config core.hooksPath ./hooks`
1. run `atom --safe .`
1. click the branch indicator on the right side of status bar and create a new branch named `pp-test`.
1. right click the project panel to add a file named `afile`
1. edit file to add 7 equals signs `=======`.
1. save file
1. stage the file in the git panel
1. add commit message and click commit button in git panel
  ![image](https://user-images.githubusercontent.com/11179873/54935263-51095c00-4ef6-11e9-8f2e-00e3b344bbcf.png)
  The commit fails because the pre-commit hook _saw_ 7 equals as a merge conflict marker and exited with a non-zero exit code, stopping the commit. Now we know that the hooks are capable of firing from atom and that the console output is reported by Atom.
1. Delete the line with the 7 equals signs and save.
1. stage and commit the file as above. The commit succeeds
1. click the push which is now visible on the status bar
    ![image](https://user-images.githubusercontent.com/11179873/54935781-67fc7e00-4ef7-11e9-89ef-f188195f26ad.png)
    ![image](https://user-images.githubusercontent.com/11179873/54936173-4223a900-4ef8-11e9-8cb2-06c924436647.png).

pre-commit hook
```bash
#!/bin/bash

echo "pre-commit checks"
./hooks/merge-markers.sh
if [ $? -gt 0 ]; then exit 11; fi
```

merge-markers.sh
```bash
#!/bin/bash

# msg is intentionally space prefixed
msg="  You have merge markers in the above files."
if [ "$1" = "pp" ]; then
    git grep -E "^[><=]{7}"
    if [ $? -eq 0 ]; then
        echo "$msg Push aborted!"
        exit 1
    fi
else
    git grep -E --cached "^[><=]{7}"
    if [ $? -eq 0 ]; then
        echo "$msg Fix them before committing."
        exit 1
    fi
fi

```
pre-push hook
```bash
#!/bin/bash

echo "pre-push checks $1 $2"
url=$( echo "$2" | tr [:lower:] [:upper:] )
if [[ $url =~ "ourorg/" ]]; then
  official_branch=$(git rev-parse --abbrev-ref HEAD | grep -E "^[a-z]{2,3}/")
  if [ -n "$official_branch" ]; then
      ./hooks/merge-markers.sh "pp"
      if [ $? -gt 0 ]; then exit 12; fi
      ./hooks/minified-build.sh
      if [ $? -gt 0 ]; then exit 15; fi
      ./hooks/js-style.sh
      if [ $? -gt 0 ]; then exit 16; fi
  else
    echo "  only initials branches are allowed on ourorg repositories. Push aborted!"
    exit 1
  fi
else
  echo "  hook skipped on push to non-ouorg repositories"
fi

```

**Expected behavior:** 
I expected to see the standard output reported by Atom. `only initials branches are allowed on ourorg repositories. Push aborted!`

**Actual behavior:** 
![image](https://user-images.githubusercontent.com/11179873/54936500-f7566100-4ef8-11e9-9ff5-330484e34041.png)

**Reproduces how often:** 
100%

### Versions

Atom    : 1.35.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
OS: Windows 10
Git:  2.20.1.windows.1

**Comment by rsese** [comment] 2019-04-02 19:55
Thanks for the report!

The issue is still open so I don't believe it's been addressed so I think this is a duplicate of https://github.com/atom/github/issues/1121?  Going to close in favor of that issue but if you're describing something different, please let me know!

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-04-02 19:55 UTC
