### ISSUE TITLE
Git identity prompt always appearing

### ISSUE THREAD

**Issue by cvande04** [atom/github#2558] opened 2020-11-11 03:30 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Hello, I am a long-time Atom user but a first-time poster. I ran into a novel bug earlier today regarding the Git package, specifically the Git identity prompt. Please let me know if the description of the problem is unclear in any way:

The Git Identity prompt appears every time I open the Git panel in Atom. It asks me to enter my Git username and email. However, I have run both `git config --global user.name` and `git config --global user.email` (including prior to the bug manifesting) and double-checking the config file shows that the values are set properly:

```
[user]
	name = (my username)
	email = (my email)
[github]
	user = (my username)
```

For a file in a repository that is initialized on Github, the Git identity panel often (but not always) pre-populates the fields with my username and email as found in the config file. For a file in a repository that has not been initialized, the name and email address fields are blank. Switching between two repositories, regardless of whether they are initialized or not, often (but not always) results in the Git identity prompt reappearing, even if I have just used it to sign in moments before switching, and even if I can initially see the Git panel for a few moments before the identity prompt appears. Sometimes, the identity panel will flicker rapidly back-and-forth between having the fields pre-populated and having them blank over the course of a few seconds. After this, trying to re-enter my username or email in the fields often results in glitches, where the character I typed appears in the field for a fraction of a second before vanishing as if I had hit the backspace key. I have tried everything in the debugging guide, including uninstalling/reinstalling Atom and disabling/re-enabling the Git package, as well as re-entering the `git config --global` values for name and email and repeatedly restarting my computer. 

My guess is that it has something to do with my Git credentials, given that it is the Git identity prompt that glitches and that sometimes the fields are not pre-populated with my name and email as I have them configured, but for the life of me I cannot figure out what it is. Running `git config user.name` or `git config user.email` brings up the correct values, regardless of repository. I do not have any local configs (i.e. I do not have `git config username` without the global flag to set any values in any of the repositories in question). Any help would be appreciated; the bug is interrupting my workflow and (in some cases) preventing me from using Atom's Git interface entirely.

### Steps to Reproduce

1. Open Atom
2. Open a file from a repository
3. Open Git tab
4 (optional). Switch between files in different repositories.

**Expected behavior:**

Git tab (unstaged/staged changes, commit message field, list of past commits) is displayed.

**Actual behavior:**

Git identity panel is displayed, sometimes after a few seconds of seeing the Git tab and sometimes not; sometimes with the fields pre-populated with my username and email and sometimes not. 

![git-issue](https://user-images.githubusercontent.com/46804326/98761329-2dcd4200-23a3-11eb-8f3b-07666c500647.jpg)

**Reproduces how often:**

95% (occasionally, switching between files of two different repositories that are both initialized will not cause the prompt to reappear).

### Versions

Atom    : 1.53.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0

apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.53.0
python 2.7.8
git 2.22.0.windows.1
visual studio

OS Name: Microsoft Windows 10 Home
Version: 10.0.19041

### Additional Information

I should note that one of the repositories is linked to Heroku, although the error is not exclusive to that one repository.

**Comment by markdynamo6** [comment] 2020-11-12 21:19
Same here (same version as @sweetsweetstefan ), but on Windows.

**Comment by smashwilson** [comment] 2020-11-12 23:39
Oh yuck, I'm sorry you're hitting this. I had a few issues like this during development but I thought I'd managed to squash them - I haven't seen it happen myself since then (across a few machines and platforms). Apparently not!

Not sure how soon I'll be able to look into a fix unfortunately (quarantine parenting, etc). I'll flag this for attention the next time I do get time, but if anyone else has the chance to investigate before me I would ❤️ a pull request here 😇 and promise a quick review!

**Comment by markdynamo6** [comment] 2020-11-13 00:04
No hassles Ash. Thanks for the quick reply.

**Comment by jakubmuransky** [comment] 2020-11-13 13:15
After upgrade to macOS BigSur this problem appears

**Comment by Alterraia** [comment] 2020-11-13 18:11
This has been happening since 2018.  They have never fixed it.  They maybe patch it, but then when they make an update to Atom, it breaks the patch and reverts back to this.

I've seen vague responses since this first started happening, but nothing actually helpful and no real resolution.  If the root of the issue is not fixed, it is going to happen again, as it is happening now, and we will be here doing this all over again.

**Comment by smashwilson** [comment] 2020-11-13 18:19
The git identity panel was added on [6 April 2020](https://github.com/atom/github/commit/d8224964a3352916fd30d3717d45a1710d0ca6a0), so if this has been "happening since 2018" that would be pretty impressive.

Are you confusing the git identity panel with something else? We have three distinct identities at play in this package - the username and email that git uses to construct commits; the token and GitHub account used to push and fetch changes to and from remotes; and the token and GitHub account used to interact with the GitHub API to fetch pull request data and review comments and the like. Have you been having problems with one of those, instead?

**Comment by Alterraia** [comment] 2020-11-13 18:22
I'm only using Atom, but the issue that I am having I have seen dated as far back as 2018.  Maybe it was called something else then or it was the previous version, but the Git Identity panel is repeating the problem that was happening before.  Putting a new face on the method to log in doesn't fix the underlying issue.  I initially google searched my issue in hopes to find a resolution, which is how I found this issue isn't new.  It's just a new version of the same issue.

**Comment by jakubmuransky** [comment] 2020-11-13 18:23
In my case is problem with "classic" Git I don't use GitHub plugin

**Comment by Alterraia** [comment] 2020-11-13 18:31
I'm new to using Git.  I used Atom then replaced the original file with my new file.  Git is more convenient.  Am I able to just bypass Atom for now and upload directly from Git?  I have things I need to push in a few hours.  It takes minutes to do, but I figure if git is up to date, then i can pull and update my files on my PC.

**Comment by smashwilson** [comment] 2020-11-13 18:39
> I initially google searched my issue in hopes to find a resolution, which is how I found this issue isn't new. It's just a new version of the same issue.

Can you link the issue you think this is a duplicate of?

**Comment by smashwilson** [comment] 2020-11-13 18:40
>  Am I able to just bypass Atom for now and upload directly from Git? I have things I need to push in a few hours. It takes minutes to do, but I figure if git is up to date, then i can pull and update my files on my PC.

Yes, of course. You can always use git on the command line (or any other git client, like GitHub Desktop) to do anything git-related.

**Comment by Alterraia** [comment] 2020-11-13 18:43
I think this is it.  It was a few days ago when I was searching it and there was a lot of school work assignments and web searches between then and now.  But the description and the problem seems identical to what I'm experiencing now, only mine is using the 2020 version.

https://github.com/atom/github/issues/1353

**Comment by smashwilson** [comment] 2020-11-13 18:45
Do you see an error like this in your development console?

> Uncaught (in promise) Error: RelayModernGraphQLTag

**Comment by Alterraia** [comment] 2020-11-13 18:48
I do not.  And that is because I've done everything right in Atom.  It's how I learned to do what I do.  While it's not as advanced, I'm able to accomplish what I need to do.

The only thing I've done, on the regular and had no issues, was have other projects open while only the one is linked to Git.  And I did create a new, unrelated repository the night prior to this all happening.

When I came on the following morning, Atom had an update ready to install and I was signed out.

**Comment by cvande04** [comment] 2020-11-13 21:24
Thanks Ash for your quick response! I think my issue is related Git, not GitHub, so while 1353 may be a similar problem, I'm not sure it is the same one.

**Comment by Alterraia** [comment] 2020-11-14 06:32
So the problem was is that when atom updated, my .git file was completely removed.  Nowhere on my PC.  Not even in the recycle bin.  Makes zero sense.

We added a new one, but still not working, so we just downloaded a new clone, and that worked fine.  The login information worked and everything.  Removed the other copy.

I really do not want to have to go through this route again.  No reason that .git file should be removed.

**Comment by jakubmuransky** [comment] 2020-11-14 08:19
I have untouched .git folder, but in git config --list name and mail missing

**Comment by joeland1** [comment] 2020-11-16 14:28
Had same issue. Fixed it by uninstalling and reinstalling atom. (Windows 10)

**Comment by jonyyz** [comment] 2020-11-16 15:36
@smashwilson I think I found the root cause of the problem.  Try creating a folder with multiple git projects and then add the folder containing the git projects to the project view and switch between them.

**Comment by jnawk** [comment] 2020-11-17 21:23
It wouldn't be nearly so annoying if you could dismiss it without having to fill it in.

Additionally - it seems to only lift values from the repo's .git/config and ignores $HOME/.gitconfig - I have user.name set globally (since my name doesn't change depending on what code I'm working on), and user.email set per repo.

**Comment by smashwilson** [comment] 2020-11-17 21:37
> It wouldn't be nearly so annoying if you could dismiss it without having to fill it in.

Just as a sidenote, even before I can get a proper fix, you should be able to do this already. Click on the mini-avatar portrait at the top-left of the git panel:

<img width="230" alt="avatar button" src="https://user-images.githubusercontent.com/17565/99453169-8ac07f00-28f2-11eb-8c89-b483934c4d82.png">

**Comment by sweetsweetstefan** [comment] 2020-11-17 21:41
I confirm that when the mini-avatar is present and I click it, Atom seems to then find the proper credentials and Git works as expected for a while.

However, the mini-avatar is not always present.  I'll keep a closer eye on that and will post again if I find a pattern.

**Comment by jnawk** [comment] 2020-11-17 22:04
Hrm.  My issue where values aren't pulled from the places appears to be windows gaslighting me, so I have nothing new to add after all.

**Comment by saschabraun** [comment] 2020-11-18 09:04
Having the same issue since Big Sur update.

**Comment by andygeorge** [comment] 2020-11-18 15:45
Seeing this happen on Fedora 33 whenever I switch between a file in a repository and another one _not_ in a repository.

**Comment by mikkopori** [comment] 2020-11-19 12:51
I've started seeing this with Atom on Ubuntu for a short time. Pretty annoying to have click 'continue' once a while even if the values are still the same & correct.

Do not have github configured.

**Comment by MrHerickS** [comment] 2020-11-19 13:01
Same issue on Big Sur, it's very very annoying

**Comment by realizelol** [comment] 2020-11-19 18:34
Hi,

I am having the same issue on windows 10. "Git Identity" window will appear on every start of atom, even if I click on my avatar
I still get back to "Git Identity" everytime. On my MacBook (10.15.7) it's more annoying because it's unusable I have had to download the beta version because stable is not stable. 👎🏻 
Both are the latest stable version 1.53.0.

best regards
realizelol

**Comment by markdynamo6** [comment] 2020-11-19 19:06
Seems like we've all confirmed that there's an issue. Anyone care to venture a fix?

**Comment by smashwilson** [comment] 2020-11-19 19:56
Oh, I've started a fix for the root cause in #2564. It's a little slow going because this isn't my day job anymore, but I'm hopeful that it won't take too much longer.

> On my MacBook (10.15.7) it's more annoying because it's unusable I have had to download the beta version because stable is not stable.

Wait. Is this not an issue on beta? That's... odd. I've been able to reproduce it easily enough on nightly.

**Comment by markdynamo6** [comment] 2020-11-19 22:36
Awesome. Cheers Ash.

**Comment by smashwilson** [comment] 2020-11-20 21:42
Doing a little digging in the history shows that #2437 already addresses most of this, and is _not_ included in the version of this package that's included in Atom stable, but _is_ already included in the current beta (and will be in the next stable release). Furthermore, I've just merged #2564, which deals with another source of odd edge cases.

This means that switching to [Atom Beta](https://atom.io/beta) or [Atom Nightly](https://atom.io/nightly) should help most of the immediate annoyance. But if you _really_ want to live on the cutting edge, run this in a command prompt or terminal:

```
apm install atom/github
```

This will install the latest commit to the default branch of this repo and load that version of the github package instead of the one that's bundled with your Atom install. It'll make Atom slightly slower to launch, but it would let you try out the very latest changes to make sure that they address the problem. And you can always undo it with `apm uninstall github` if it becomes a problem.

**Comment by kalwalt** [comment] 2020-11-24 10:13
I have this issue too, I thought that i was the only one. I have installed atom on OpenSuse tumbleweed, installed with snapd, installed atom-github atom-git-plus plugins. I would try your suggested solution @smashwilson, hoping that will fix it.

**Comment by gotwastedaf** [comment] 2020-11-24 11:11
Same issue just after update Big Sur

**Comment by amirhosseinhpv** [comment] 2020-11-25 11:51
same problem here, windows 10 x64 Atom latest

**Comment by kalwalt** [comment] 2020-11-25 12:09
@smashwilson i can't install with:

`apm install atom/github` 

i receive a long list of errors, i will report here a log file.

**Comment by ggstuart** [comment] 2020-11-25 13:45
Same problem on ubuntu 18.04, also cannot install atom/github

**Comment by smashwilson** [comment] 2020-11-25 14:46
Ahhh right... my first guess is that you're likely missing build tools. This package includes dependencies with C/C++ components, most notably [keytar](https://github.com/atom/node-keytar), so your system needs to be able to compile these properly in order to install it in dev mode.

The way to do that depends on your operating system. It's a strict subset of the build prerequisites listed [in the Atom flight manual](https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/) for your platform - on Ubuntu, you'll need at least `build-essential` and `libsecret-1-dev` - so following those instructions should get you running.

If it's too much hassle, I'm hoping to have this in nightly in a few days.

**Comment by kalwalt** [comment] 2020-11-25 14:49
> Ahhh right... my first guess is that you're likely missing build tools. This package includes dependencies with C/C++ components, most notably [keytar](https://github.com/atom/node-keytar), so your system needs to be able to compile these properly in order to install it in dev mode.
> 
> The way to do that depends on your operating system. It's a strict subset of the build prerequisites listed [in the Atom flight manual](https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/) for your platform - on Ubuntu, you'll need at least `build-essential` and `libsecret-1-dev` - so following those instructions should get you running.
> 
> If it's too much hassle, I'm hoping to have this in nightly in a few days.

Thank you for the answer @smashwilson ! since i am on OpenSuse i will search for corresponding packages to install.

**Comment by smashwilson** [comment] 2020-11-27 12:56
I'm going to close this because the fix is merged and the GitHub package update will be in the next nightly build. (It looks like the nightly build is having some unrelated issues, so it isn't published there yet.)

Thanks for the reports and your patience, everyone.

**Closed by smashwilson** 2020-11-27 12:56 UTC

**Comment by imperialguy** [comment] 2020-12-01 12:28
Is this fix in yet? I'm still seeing the problem.

**Comment by jnawk** [comment] 2020-12-03 22:22
Keen to see if this fix resolves the issue I'm seeing - after further observation, it seems that when I have my name and email split over the global (for the name) and the per repo (for the email), my global config gets rewritten when I dismiss the identity window - name disappears (since it's not in the local config), and email is set to what was in the local config.

Any idea when this will be released?

**Comment by Alterraia** [comment] 2020-12-06 20:07
I submitted this and when it came up for voting today, it was immediately
voted out in less than 24 hours.  I have nominations older than that that
are still in voting.

The person YOU accused me of harassing is using his automated program on
his multiple accounts to kill nominations he does not like.

The picture I provided shows a bent sign.  It is not new.  It is not
seasonal.  It has weather damage.

It is CLEARLY on the bike path.

You need to handle this as you accused me of harassing him but he is the
one doing it covertly because he is legally restrained from coming near my
home.

This is not near my house.  It is a 5 minute walk.  This is a legitimate
nomination and it meets your criteria.

Please respond with how you will help me do this.  I have multiple
nominations up and they are ALL legit nominations that meet your criteria.
I don’t waste my time doing fake nominations.

I beg you to take charge of your service and stop letting this monster keep
control.

**Comment by Alterraia** [comment] 2020-12-06 20:09
Oops. RBIs is the wrong email. Lol

**Comment by ivanblack19** [comment] 2020-12-11 06:42
Not fixed in ightly also - MacOs

**Comment by gothicserpent** [comment] 2020-12-11 23:49
happens for me in 1.53

**Comment by smashwilson** [comment] 2020-12-11 23:52
Yeah, I got stalled on some unrelated test crashing in the Atom build, and also had a bunch of stuff to deal with for Universe at my Real Job. It's still on the way though, and the core team knows about it.

**Comment by gothicserpent** [comment] 2020-12-12 00:01
thank you

**Comment by nikahmadz** [comment] 2020-12-26 17:42
That thing going from bad to worst. It start blinking and preventing me to type my name and email into it. Super annoying

**Comment by smashwilson** [comment] 2020-12-26 19:58
@nikahmadz Off-topic: see #2594. Please subscribe there instead of commenting on a closed issue.
