### ISSUE TITLE
Uncaught Error: ~/Downloads/Travel document for  WHEELER - KIJAN CAMERON - 4ZZVCG.pdf does not be...

### ISSUE THREAD

**Issue by Imelmz2018** [atom/github#997] opened 2017-07-01 16:30 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [github](https://github.com/atom/github) package 0.3.3

### Stack Trace

Uncaught Error: /Users/elmzduh/Downloads/Travel document for  WHEELER - KIJAN CAMERON - 4ZZVCG.pdf does not belong to repo null

```
At /private/var/folders/j2/hwh5my2s38l6rg3g5d5j_3880000gn/T/AppTranslocation/8E88A21A-A611-49C6-A530-5866075112D8/d/Atom.app/Contents/Resources/app/node_modules/github/lib/controllers/root-controller.js:807

Error: /Users/elmzduh/Downloads/Travel document for  WHEELER - KIJAN CAMERON - 4ZZVCG.pdf does not belong to repo null
    at RootController.viewChangesForCurrentFile (/private/var/folders/j2/hwh5my2s38l6rg3g5d5j_3880000gn/T/AppTranslocation/8E88A21A-A611-49C6-A530-5866075112D8/d/Atom.app/Contents/Resources/app/node_modules/github/lib/controllers/root-controller.js:807:19)
    at RootController.viewUnstagedChangesForCurrentFile (/private/var/folders/j2/hwh5my2s38l6rg3g5d5j_3880000gn/T/AppTranslocation/8E88A21A-A611-49C6-A530-5866075112D8/d/Atom.app/Contents/Resources/app/node_modules/github/lib/controllers/root-controller.js:812:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/private/var/folders/j2/hwh5my2s38l6rg3g5d5j_3880000gn/T/AppTranslocation/8E88A21A-A611-49C6-A530-5866075112D8/d/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/private/var/folders/j2/hwh5my2s38l6rg3g5d5j_3880000gn/T/AppTranslocation/8E88A21A-A611-49C6-A530-5866075112D8/d/Atom.app/Contents/Resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/private/var/folders/j2/hwh5my2s38l6rg3g5d5j_3880000gn/T/AppTranslocation/8E88A21A-A611-49C6-A530-5866075112D8/d/Atom.app/Contents/Resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/private/var/folders/j2/hwh5my2s38l6rg3g5d5j_3880000gn/T/AppTranslocation/8E88A21A-A611-49C6-A530-5866075112D8/d/Atom.app/Contents/Resources/app/src/atom-environment.js:1320:34)
    at EventEmitter.outerCallback (/private/var/folders/j2/hwh5my2s38l6rg3g5d5j_3880000gn/T/AppTranslocation/8E88A21A-A611-49C6-A530-5866075112D8/d/Atom.app/Contents/Resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -3:05.8.0 core:copy (input.hidden-input)
     -2:53.5.0 core:paste (input.hidden-input)
     -2:51.1.0 editor:newline (input.hidden-input)
     -2:41.7.0 core:copy (input.hidden-input)
     -2:17 encoding-selector:show (span.syntax--source.syntax--java)
     -2:01.3.0 editor:newline (input.hidden-input)
     -2:00.2.0 find-and-replace:show (input.hidden-input)
     -1:24.8.0 editor:newline (input.hidden-input)
     -1:24.2.0 core:backspace (input.hidden-input)
     -1:23 core:paste (input.hidden-input)
     -1:21.7.0 editor:newline (input.hidden-input)
     -1:05.8.0 core:paste (input.hidden-input)
     -1:01.4.0 core:confirm (button.btn.btn-all)
  2x -0:46.5.0 core:paste (input.hidden-input)
     -0:31.8.0 core:copy (input.hidden-input)
     -0:17.2.0 github:view-unstaged-changes-for-current-file (span.syntax--text.syntax--plain.syntax--null-grammar)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2017-07-03 22:04
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/github/issues/950. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-07-03 22:04 UTC
