### ISSUE TITLE
Does not work for Github subfolder within project directory

### ISSUE THREAD

**Issue by aurovrata** [atom/github#1149] opened 2017-09-05 11:01 UTC
I develop WordPress plugins and as such my porject directory is then entire WordPress root folder, which means that my github folder is acatually a sub-folder within the wp-content/plugins/ folder.

Is there anyway to get githb.atom.io package to work from a given sub-folder?

**Comment by smashwilson** [comment] 2017-10-08 15:46
If you open and focus an editor for any file within your `wp-content/plugins` folder, the github package should find the correct repository. We find the "active repo" by walking up the directory tree looking for `.git` folders, just as git does.

**Comment by ericbiewener** [comment] 2017-10-10 01:38
@smashwilson This doesn't appear to happen for me. I have a parent folder open that contains 3 subfolders, each of which have top-level `.git` directories. Atom doesn't recognize them.

**Comment by aurovrata** [comment] 2017-10-10 08:05
doesn't seem to work,  I am using linked folders to my github repo, as I use these repo files in several projects.  Could this be the reason why it doesn't work?

**Comment by ericbiewener** [comment] 2017-10-10 16:59
I don't think that's the issue. I'm not using symlinks and I have the same problem.

**Comment by smashwilson** [comment] 2017-10-10 19:23
Oh, interesting. I can repro now too. Maybe we regressed on this at some point 🤔

**Comment by Ismail-elkorchi** [comment] 2017-12-27 15:26
@smashwilson Any progress ? This must issue must be a priority, since every Wordpress developer who wish to benefit from [ide-php](https://github.com/atom/ide-php) features must set the project directory the WordPress root folder as @aurovrata said.

**Comment by Ismail-elkorchi** [comment] 2018-01-13 03:53
cc @kuychaco @BinaryMuse @daviwil @50Wliu

**Comment by 50Wliu** [comment] 2018-01-13 04:48
@BinaryMuse Does the github package use separate logic, or should this be closed as a duplicate of atom/atom#2203?

**Comment by szeck87** [comment] 2018-04-03 17:09
From what I can tell, only the top level folder is searched for a `.git` directory when adding a folder to the project.  If I put a breakpoint in this function, https://github.com/atom/github/blob/3ab9dbe73d9f7bec129a617e660c21a17d833e90/lib/git-shell-out-strategy.js#L343-L356, and open a single folder that contains three git directories, the only time it hits the breakpoint is when the directory is the top level one.

Consider this structure and I add Folder1 to my project workspace:
```
Folder1 (no .git folder, so state resolves to empty)
   folderA (has a .git folder, but never looked at)
   folderB (has a .git folder, but never looked at)
   folderC (has a .git folder, but never looked at)
```

**Comment by camlafit** [comment] 2018-12-20 16:30
Hello

Looks related to #1835
Any evolves about this feature ? It's a bit ugly to add any subdirectory as a multiprojects

**Comment by lgeiger** [comment] 2019-04-02 22:39
> Oh, interesting. I can repro now too. Maybe we regressed on this at some point 🤔

@smashwilson Since you are able to reproduce this has there been any progress on this issue?

I started using git submodules heavily today and this makes it quite frustrating to use the github plugin which previously worked for me like a charm. It seams a lot of people are having this issue too (#1835).

Strangely enough, Atom recognizes submodules just fine, when the are also added as a top level folder:
![Kapture 2019-04-02 at 23 13 55](https://user-images.githubusercontent.com/13285808/55440671-56bf0b80-55a0-11e9-9a56-bb615bd8b212.gif)

**Comment by jrial** [comment] 2019-04-03 12:29
It also seems to jumble up the contents of the .gitignore, applying the top-level .gitignore to subprojects. Not sure if that falls within this issue, or if I should open a separate one, so let me know if you'd like me to move this post to its own issue.

In the screenshot: the top-level project contains a .gitignore that hides settings_local.py (so we don't accidentally commit local configs). The subrepo "djangoconf" contains all configurations for our apps, and as such does not ignore that filename. However, I am unable to see settings_local.py when I expand the subrepo in the tree view.

![screenshot_submodule_gitignore](https://user-images.githubusercontent.com/570247/55478226-6e87a580-561b-11e9-8475-9874f085d78d.png)

**Comment by peterse** [comment] 2019-12-11 15:55
I'm also having this issue. Any update would be appreciated

**Comment by FXschwartz** [comment] 2020-01-16 14:29
I am having this issue as well. My project contains a parent directory and then multiple sub directories which are all their own repositories.

**Comment by gunsluo** [comment] 2020-09-01 10:00
the same issue for me.   my repo have a `root  go mod` and multiple `sub directories go mod` file.    

test repo: `github.com/gunsluo/test2`

run: GO111MODULE=on go get github.com/gunsluo/test2@v1.1.0. it works fine. 

but run:  GO111MODULE=on go get github.com/gunsluo/test2/log@v1.1.0
error message: 
```
go get github.com/gunsluo/test2/log@v1.1.0: module github.com/gunsluo/test2@v1.1.0 found, but does not contain package github.com/gunsluo/test2/log
```

**Comment by utkarshgupta137** [comment] 2020-12-04 23:38
I'm not able to reproduce this issue on Atom 1.53. If anyone can help me understand, I'll try to look into it. Here's what I understand the issue is/was:
Whenever there is a git repo, which is not a top-level folder, it doesn't get detected as repo properly. Further, if any parent folder/git repo contains .gitignore, it is also applied to submodules.

From my findings: This issue is present in many core packages and a few community packages. I've raised PRs for the ones I know about, see https://github.com/atom/github/issues/1835#issuecomment-739073973.
But this issue has never actually affected the github package itself (i.e. git & github sidebars).

**Comment by utkarshgupta137** [comment] 2020-12-04 23:41
@lgeiger the issue you're describing is with tree-view package not github package. As a temporary fix, please add all the actually git repos as project folders at the top of the stack. Then add any main folders you have. This case as well will be fixed through my PRs.

**Closed** 2022-01-10 12:54 UTC
