### ISSUE TITLE
Initialize the git in the working directory

### ISSUE THREAD

**Issue by mittalyashu** [atom/github#1298] opened 2018-01-30 15:45 UTC
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]?
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?
* Have you checked the FAQs on the [message board][message-board] for common solutions?
* Have you checked that your issue [isn't already filed][already-filed]?

[x]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[x]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[x]: https://github.com/atom/github/issues

### Description, Steps to Reproduce

https://www.useloom.com/share/97f61c1456654b3988999ef8aa7d7cbb

**Expected behavior:**

![image](https://user-images.githubusercontent.com/29014463/35575423-5c5c1694-0602-11e8-87dd-df09137c70f8.png)

Here it should show the location where the directory is *(because we want to initialize the git in the working directory only)*

**Actual behaviour:**

Shows the user directory.

**Reproduces how often:**

100%

### Versions

Version: 1.23.2
Windows 10

**Comment by BinaryMuse** [comment] 2018-01-30 21:40
Thanks for the issue, but this appears to be a duplicate of https://github.com/atom/github/issues/1237. Follow along there for more.

**Closed by BinaryMuse** 2018-01-30 21:40 UTC
