### ISSUE TITLE
Unstaged/staged changes tabs keeps popping up

### ISSUE THREAD

**Issue by Ben3eeE** [atom/github#1444] opened 2018-05-07 08:52 UTC
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]?
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?
* Have you checked the FAQs on the [message board][message-board] for common solutions?
* Have you checked that your issue [isn't already filed][already-filed]?

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

The unstaged changes tab doesn't want me to change pane items.

**Note:** running the master version of the github package.

![github unstaged changes](https://user-images.githubusercontent.com/1058982/39692164-5c7fc63c-51e0-11e8-943a-f7f33d857583.gif)

### Steps to Reproduce

1. `apm install atom/github`
2. Open the unstaged changes tab
3. Try to switch to another pane item by clicking the tab of another item

**Expected behavior:**

Switching to the tab I clicked on

**Actual behavior:**

Switches back to the unstaged changes tab.

**Reproduces how often:**

100%

### Versions

Atom 1.28.0-dev-a3631f0da
GitHub-package@https://github.com/atom/github/commit/8b0226d01a85db52c1634d9844241e0b0d46e082

**Comment by Ben3eeE** [comment] 2018-05-18 06:15
@smashwilson https://github.com/atom/github/pull/1472 improves on this but I still see the behavior in two cases:

1. Open The unstaged changes tab and click on another tab. The first time I try to change tabs it changes back to the unstaged changes tab. Subsequent changes work as expected.

![github unstaged changes case 1](https://user-images.githubusercontent.com/1058982/40218881-6c38892e-5a73-11e8-925f-6302c9edd477.gif)

2. If you have the unstaged changes tab open in the left pane and are focused on a file in the right pane when trying to change files it always switches back.

![github unstaged changes case 2](https://user-images.githubusercontent.com/1058982/40218921-90706e92-5a73-11e8-9a15-217c23754131.gif)

**Comment by smashwilson** [comment] 2018-05-18 14:37
@Ben3eeE I can't reproduce either case from d4b8ae92f109e.

It could be a Mac vs. Windows thing?

**Comment by Ben3eeE** [comment] 2018-05-18 15:06
@smashwilson Yeah that's possible. I'm also running a bunch of community packages. But I was on the same commit having the github package linked from master.

This was on Windows 7. I can recheck without community packages and a fresh build from atom/atom on Monday. And check if I can narrow it down somehow.

The behavior is much better now anyway 💯

**Comment by Ben3eeE** [comment] 2018-05-21 10:42
@smashwilson I noticed that I only see this if the `Unstaged Changes` tab is pending. Do you have the `Allow Pending Pane Items` setting disabled? That would explain why you can't reproduce.

**Comment by smashwilson** [comment] 2018-05-30 13:32
Closing this because #1488 _should_ deal with it Once And For All :tm:. Re-open at will if you see this pop up with atom/github >= 0.15.2.

**Closed by smashwilson** 2018-05-30 13:32 UTC
Labels: triaged

**Comment by dark-panda** [comment] 2018-12-21 17:48
I've been seeing this lately with 0.22.2 on Atom 1.33 and 1.33.1.
