### ISSUE TITLE
Uncaught Error: D:/Xampp\htdocs\pu8wx\public\js\profiles\enterprise.js does not belong to repo null

### ISSUE THREAD

**Issue by Ale-cc** [atom/github#972] opened 2017-06-23 00:59 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0-beta1 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [github](https://github.com/atom/github) package 0.3.3

### Stack Trace

Uncaught Error: D:\Xampp\htdocs\pu8wx\public\js\profiles\enterprise.js does not belong to repo null

```
At C:\Users\jacki\AppData\Local\atom\app-1.19.0-beta1\resources\app\node_modules\github\lib\controllers\root-controller.js:807

Error: D:\Xampp\htdocs\pu8wx\public\js\profiles\enterprise.js does not belong to repo null
    at RootController.viewChangesForCurrentFile (~/AppData/Local/atom/app-1.19.0-beta1/resources/app/node_modules/github/lib/controllers/root-controller.js:807:19)
    at RootController.viewStagedChangesForCurrentFile (~/AppData/Local/atom/app-1.19.0-beta1/resources/app/node_modules/github/lib/controllers/root-controller.js:816:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.0-beta1/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.0-beta1/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.19.0-beta1/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.19.0-beta1/resources/app/src/atom-environment.js:1344:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.19.0-beta1/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
 15x -0:55.5.0 intentions:highlight (input.hidden-input)
     -0:41.4.0 find-and-replace:show (input.hidden-input)
     -0:35.5.0 find-and-replace:find-next (input.hidden-input)
     -0:09.2.0 github:view-staged-changes-for-current-file (div.line)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-minify 0.8.0 
autoprefixer 3.7.0 
busy-signal 1.4.3 
csscomb 0.3.1 
docblockr 0.10.5 
emmet 2.4.3 
highlight-line 0.12.0 
highlight-selected 0.13.1 
intentions 1.1.2 
jquery-snippets 11.0.0 
linter 2.2.0 
linter-eslint 8.2.1 
linter-ui-default 1.6.2 
minimap 4.28.2 
simplified-chinese-menu 5.3.4 
tortoise-svn 0.5.1 
vue-snippets 0.6.0 
```

**Comment by BinaryMuse** [comment] 2017-06-25 17:52
This looks like a duplicate of https://github.com/atom/github/issues/950

**Closed by BinaryMuse** 2017-06-25 17:52 UTC
Labels: uncaught-exception
