### ISSUE TITLE
Uncaught TypeError: Cannot read property 'parentNode' of null

### ISSUE THREAD

**Issue by nicolas-f** [atom/github#834] opened 2017-05-17 12:51 UTC
[Enter steps to reproduce:]

1. Try to "Discard selection" multiple times

**Atom**: 1.18.0-beta0 x64
**Electron**: 1.3.15
**OS**: Windows 7 64 bits
**Thrown From**: [github](https://github.com/atom/github) package 0.0.9

### Stack Trace

Uncaught TypeError: Cannot read property 'parentNode' of null

```
At D:\fortin\AppData\Local\atom\app-1.18.0-beta0\resources\app\node_modules\github\lib\views\file-patch-view.js:206

TypeError: Cannot read property 'parentNode' of null
    at requestAnimationFrame (~/AppData/Local/atom/app-1.18.0-beta0/resources/app/node_modules/github/lib/views/file-patch-view.js:206:1)
```

### Commands

```
     -5:10.5.0 core:backspace (input.hidden-input)
     -2:32.1.0 tabs:close-other-tabs (div.title)
  2x -1:49.6.0 editor:select-to-first-character-of-line (input.hidden-input)
     -1:49.2.0 core:backspace (input.hidden-input)
     -1:46.6.0 core:save (input.hidden-input)
     -1:41.1.0 core:move-right (input.hidden-input)
 11x -1:40.9.0 core:move-left (input.hidden-input)
 10x -1:40 core:move-right (input.hidden-input)
     -1:38.3.0 core:delete (input.hidden-input)
 10x -1:37.9.0 core:move-right (input.hidden-input)
     -1:35.6.0 core:save (input.hidden-input)
     -1:32.4.0 snippets:next-tab-stop (input.hidden-input)
     -1:32.4.0 snippets:expand (input.hidden-input)
     -1:32.4.0 editor:indent (input.hidden-input)
     -1:29.2.0 core:undo (input.hidden-input)
  4x -0:35.4.0 github:discard-selected-lines (span.)
```

### Non-Core Packages

```
atom-beautify 0.29.24 
```

**Comment by BinaryMuse** [comment] 2017-05-17 12:54
This appears to be a duplicate of https://github.com/atom/github/issues/822.

**Closed by BinaryMuse** 2017-05-17 12:54 UTC
