### ISSUE TITLE
Can't login to GitHub from Atom

### ISSUE THREAD

**Issue by corbincavolt** [atom/github#1353] opened 2018-03-14 23:35 UTC
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]?
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?
* Have you checked the FAQs on the [message board][message-board] for common solutions?
* Have you checked that your issue [isn't already filed][already-filed]?

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

Hi, I'm not able to login to the GitHub via the GitHub panel in Atom.  I click the link (github.atom.io/login) to generate the token, copy that token from the website and paste it into the token field via ctrl+v (there's no right-click option, which is documented in #899).  All that works fine, the issue is when I click the login button, nothing happens.  I've tried to troubleshoot this several ways:

- The project I initially tried this in belongs to an organization I'm a member of; to ensure there wasn't a permissions issue (not sure if this would matter, but figured I'd try anyway), I tried the same procedure documented above in a project that I'm the sole owner of.  Still no luck.
- I tried uninstalling Atom then reinstalling it.  At this point I hadn't done anything with my User Profile, so I'm not sure if this would've fixed anything, but I tried it anyway.
- Per the debugging guide, I tried using Safe Mode, clearing saved state, and resetting to factory defaults, none of which made a difference.  I checked for linked packages; I have none.  Lastly, I opened Chrome Developer Tools, went to the console and saw the following error:  "<embedded>:267311 Uncaught (in promise) Error: RelayModernGraphQLTag".  There's a lot more there (looks mostly like JSON and references to module locations but I'm no expert) but I wasn't sure if I needed to scrub the log for PII before uploading it.  The 267311 listed above refers to invariant.js.

### Steps to Reproduce

1. Click the link (github.atom.io/login) to generate the token
2. Copy that token from the website and paste it into the token field
3. Click login button, nothing happens

**Expected behavior:**

[What did you expect to happen?]

That I would be logged into GitHub.

[What actually happened instead?]

Nothing.

[What percentage of the time does this happen?]

100% of the time.

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.24.1
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0

Windows:  Windows 10 Enterprise 2016 LTSB

### Additional Information

Please include any additional information, configuration or data that might be necessary to reproduce the issue. Screenshots, if appropriate, are helpful as well.

If your issue involves a repository, and that repository is public, please include a link to it.

**Comment by rsese** [comment] 2018-03-15 00:27
Thanks for contributing!

We noticed that this is a duplicate of https://github.com/atom/github/issues/1340 which was fixed in https://github.com/atom/github/pull/1344 - the fix will be available in an upcoming release.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-03-15 00:27 UTC

**Comment by mcnabb0303** [comment] 2018-11-26 17:59
## still doesn't work on 
apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.2
python 2.7.15
git 2.19.0

**Comment by rsese** [comment] 2018-11-27 06:51
@mcnabb0303 - please open a new issue with the issue template filled out and we'll take a look.

**Comment by scottaw66** [comment] 2020-01-11 21:34
I have this currently with 
```
Atom    : 1.41.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.41.0
python 2.7.16
git 2.21.0
```

**Comment by d2gdev** [comment] 2021-07-12 03:33
Still doesnt work, three years later.

**Comment by Atlas-Night-Out** [comment] 2021-07-27 14:01
I'm an unable too lastest version of atom too 1.58.0 seems to log in but no files show on GitHub when I stage and commit them any clues why, please?

**Comment by jmendoza-es** [comment] 2021-11-02 11:54
Same here, can't get it to work :(

**Comment by ajsauter** [comment] 2021-11-05 19:49
So glad I'm not alone. Not able to log on at all.

**Comment by iamh2o** [comment] 2021-11-19 05:04
sadly, me too

**Comment by Singh2236** [comment] 2021-11-22 08:28
as of Nov 22, 2021, the problem still exists.

**Comment by hadi175** [comment] 2022-01-08 10:09
2022 and the problem still exists.

**Comment by dccupp** [comment] 2022-03-24 02:55
The problem still exists

**Comment by John-Hollingum** [comment] 2022-04-25 08:14
> Thanks for contributing!
> 
> We noticed that this is a duplicate of #1340 which was fixed in #1344 - the fix will be available in an upcoming release.
> 
> Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.
> 
> For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

The issue is *not* a duplicate of 1340, as 1340 describes the attempted login resulting in an error message. The problem I am seeing is, as described above, that no response at all comes after clicking on the login button. The display remains exactly as it did before clicking the button.

**Comment by John-Hollingum** [comment] 2022-04-25 08:15
This is a more urgent problem as GitHub have recently removed the ability to authenticate by password

**Comment by Tachytaenius** [comment] 2022-05-10 10:34
Hey, I'm getting this too on Windows

**Comment by Kishou4rima** [comment] 2022-07-09 19:39
Still not working

**Comment by Tachytaenius** [comment] 2022-07-09 20:42
Sadly, atom is going EoL so it might be time to look into alternative editors anyway :(

**Comment by Kishou4rima** [comment] 2022-07-09 22:33
What really?

**Comment by MixwelInc** [comment] 2022-08-28 18:19
gj guys it is not working even after 4 years :)

**Comment by ioancata25** [comment] 2022-09-28 18:40
09.2022 The problem still exist :(
