### ISSUE TITLE
Uncaught Error: D:/AppData\Local\Temp\1-index.php does not belong to repo null

### ISSUE THREAD

**Issue by Blessun** [atom/github#1049] opened 2017-07-21 06:57 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [github](https://github.com/atom/github) package 0.3.3

### Stack Trace

Uncaught Error: D:\AppData\Local\Temp\1-index.php does not belong to repo null

```
At C:\Users\Сергей\AppData\Local\atom\app-1.18.0\resources\app\node_modules\github\lib\controllers\root-controller.js:807

Error: D:\AppData\Local\Temp\1-index.php does not belong to repo null
    at RootController.viewChangesForCurrentFile (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/github/lib/controllers/root-controller.js:807:19)
    at RootController.viewUnstagedChangesForCurrentFile (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/github/lib/controllers/root-controller.js:812:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.18.0/resources/app/src/atom-environment.js:1320:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.18.0/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:25.1.0 core:backspace (input.hidden-input)
     -1:14.6.0 autocomplete-plus:confirm (input.hidden-input)
  4x -1:00.5.0 core:move-right (input.hidden-input)
     -0:48.7.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:48.7.0 editor:newline (input.hidden-input)
     -0:35.8.0 core:move-down (input.hidden-input)
     -0:35 autocomplete-plus:confirm (input.hidden-input)
 26x -0:33.8.0 intentions:highlight (input.hidden-input)
     -0:32.2.0 emmet:balance-outward (input.hidden-input)
     -0:31.1.0 intentions:highlight (input.hidden-input)
     -0:30.9.0 emmet:expand-abbreviation (input.hidden-input)
     -0:29.9.0 intentions:highlight (input.hidden-input)
     -0:29.7.0 core:undo (input.hidden-input)
     -0:28.7.0 intentions:highlight (input.hidden-input)
     -0:28.3.0 emmet:balance-outward (input.hidden-input)
     -0:18.8.0 github:view-unstaged-changes-for-current-file (span.syntax--constant.syntax--other.syntax--php)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
autocomplete-paths 1.0.5 
busy-signal 1.4.3 
emmet 2.4.3 
highlight-selected 0.13.1 
intentions 1.1.2 
linter 2.2.0 
linter-ui-default 1.6.3 
minimap 4.29.0 
modx-revolution 1.1.3 
monokai 0.24.0 
monokai-seti 0.9.0 
open-recent 5.0.0 
pigments 0.39.1 
seti-ui 1.9.0 
simplified-russian-menu 1.3.0 
twilight 0.3.0 
```

**Comment by rsese** [comment] 2017-07-21 17:31
Thanks for taking the time to contribute!

We noticed that this looks like a duplicate of https://github.com/atom/github/issues/950. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-07-21 17:31 UTC
