### ISSUE TITLE
Choosing changed file shows "File has no contents" when file definitely has changes

### ISSUE THREAD

**Issue by bbugh** [atom/github#1422] opened 2018-04-25 14:24 UTC
### Description

If I single click on an item in the Unstaged Changes area (that definitely has changes), I see "File has no contents", but when I do "git diff" from the terminal, it has changes.

### Steps to Reproduce

Uncertain how to reproduce reliably, as it seems to happen completely at random. 

1. Click a file under "unstaged changes"
2. Observe

Closing the Git bar doesn't change it, however, these things do fix the problem:

1. making an additional change to the file
2. restarting Atom
3. reloading the Atom window with "Window: Reload"

**Expected behavior:**

It shows the diff contents.

**Actual behavior:**

It says "File has no contents" instead.

**Reproduces how often:**

At least once per work day, small percentage of the usage time but frequent enough in practice.

### Versions

Atom    : 1.26.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.0
python 2.7.10
git 2.16.1

MacOS 10.12.6 

### Additional Information

Atom says file has no contents:

<img width="586" alt="pasted_image_4_25_18__9_08_am" src="https://user-images.githubusercontent.com/438465/39251202-55fa7a86-4868-11e8-9cac-c0d31bc84e09.png">

Diff definitely has contents:

<img width="1084" alt="pasted_image_4_25_18__9_16_am" src="https://user-images.githubusercontent.com/438465/39251610-5a59b19a-4869-11e8-91a1-7dbb04f22070.png">

**Comment by rsese** [comment] 2018-04-25 20:05
Thanks for the report - just a few questions to try and get more details:

* Though I know it can be difficult to say since the behavior happens randomly, have you ever observed it while running in safe mode (`atom --safe`)?
* Have you seen this behavior in multiple repositories or just a particular one? 
  * Relatedly, are you able to reproduce in a public project that we can try?
* Does it matter how many changes you have?
* When you see this behavior, are there any errors in [devtools console](https://flight-manual.atom.io/hacking-atom/sections/debugging/#check-for-errors-in-the-developer-tools)?

**Comment by Arcanemagus** [comment] 2018-05-26 05:57
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/github/issues/1422#issuecomment-384416784. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by Arcanemagus** 2018-05-26 05:57 UTC
Labels: more-information-needed
