### ISSUE TITLE
Spell check in the Git commit message editor

### ISSUE THREAD

**Issue by manasesjesus** [atom/github#2208] opened 2019-07-16 11:35 UTC
## Summary

By clicking on the Git tab on the bottom-right corner, it opens the panel of the built-in feature for Git. It shows Unstaged/Staged changes and a textbox of the **commit message editor**. 
On macOS systems, the common UX is to have a built-in spell checker, but this git textbox doesn't have it, yet :)

## Motivation

To keep the same UX and avoid typos on commit messages (they are annoying and can be misunderstood sometimes).

## Tech specs

macOS 10.14.5 Mojave
Atom 1.38.2

**Comment by rsese** [comment] 2019-07-16 16:55
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/github/issues/1071 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-07-16 16:55 UTC

**Comment by manasesjesus** [comment] 2019-07-16 22:38
Thanks for the quick reply. I subscribed to #1071 although it's a bit disappointing to see that the issue has been in the backlog for almost two years...
