### ISSUE TITLE
Moving cursor in commit message box causes words to dance around 🕺

### ISSUE THREAD

**Issue by jasonrudolph** [atom/github#1046] opened 2017-07-19 18:49 UTC
### Description

Moving the cursor in the commit box causes lines to words to dance around between lines.

![demo](https://user-images.githubusercontent.com/2988/28384019-2904876e-6c91-11e7-918c-4377dd3182e7.gif)

### Steps to Reproduce

1. Enter the following text (admittedly contrived) in the commit message field:

    ```
    Commit all the things. They're really good things. We want them

    We want the editor and the buffer to stop sending/receiving keystrokes because the thingy before we destroy the editor
    ```

2. Move the cursor and observe the text wrapping/unwrapping

**Expected behavior:**

The lines of text should remain static (i.e., no change to which words are shown on which lines) as you move the cursor

**Actual behavior:**

The lines of text change as you move the cursor

**Reproduces how often:**

100%

### Versions

- github package v0.3.8
- macOS 10.12.5

```
$ atom --version
Atom    : 1.20.0-dev-3d02234cb
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

```
$ apm --version
apm  1.18.2
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.13.2
```

**Comment by jasonrudolph** [comment] 2017-07-19 18:50
FYI @as-cii: Here's an issue for the behavior we observed together earlier today.

**Comment by 50Wliu** [comment] 2017-07-19 19:58
No repro for me on Windows 10 and 1.20.0-dev-d51ed933e.  I also get a scrollbar when pasting that text in.

**Comment by 50Wliu** [comment] 2017-10-04 19:52
I'm pretty sure this is the same bug as https://github.com/atom/atom/issues/15685.  What do you think @jasonrudolph?

**Comment by jasonrudolph** [comment] 2017-10-04 20:35
> I'm pretty sure this is the same bug as atom/atom#15685. What do you think @jasonrudolph?

@50Wliu: I think you might be right about that.

**Comment by Arcanemagus** [comment] 2018-05-04 16:08
Closing this as a duplicate of https://github.com/atom/atom/issues/17268, mainly because there has been some great diagnosis posted there and simpler reproduction steps than were in https://github.com/atom/atom/issues/15685.

**Closed by Arcanemagus** 2018-05-04 16:08 UTC
