### ISSUE TITLE
Github tab token login button no response after update to 1.24.1

### ISSUE THREAD

**Issue by HaoyangFan** [atom/github#1346] opened 2018-03-11 07:14 UTC
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]?
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?
* Have you checked the FAQs on the [message board][message-board] for common solutions?
* Have you checked that your issue [isn't already filed][already-filed]?

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

I also get very similar issue as described in [#16924](https://github.com/atom/atom/issues/16924)
when I try to toggle git tab, it asks me to enter the token generated from https://github.atom.io/auth/github_package/token. However, after I copy-paste the token, when I click on the `login` button, there is no response at all. 
I am using
`MacOS 10.13.3` 
`atom 1.24.1 x 64`
`apm  1.18.12`

I can use git via atom without any error before atom updates to 1.24.1. 

I also get error message:
`Uncaught Invariant Violation: RelayModernGraphQLTag: Expected an request, got {"fragment":{"argumentDefinitions":[{"kind":"LocalArgument","name":"repoOwner","type":"String!","defaultValue":null},{"kind":"LocalArgument","name":"repoName","type":"String!","defaultValue":null},{"kind":"LocalArgument","name":"branchName","type":"String!","defaultValue":null}],"kind":"Fragment","metadata":null,"name":"PrInfoControllerByBranchQuery","selections":[{"kind":"LinkedField","alias":null,"args":[{"kind":"Variable","name":"name","variableName":"repoName","type":"String!"},{"kind":"Variable","name":"owner","variableName":"repoOwner","type":"String!"}],"concreteType":"Repository","name":"repository","plural":false,"selections":[{"kind":"FragmentSpread","name":"PrSelectionByBranchContainer_repository","args":null}],"storageKey":null}],"type":"Query"},"id":null,"kind":"Batch","metadata":{},"name":"PrInfoControllerByBranchQuery","query":{"argumentDefinitions":[{"kind":"LocalArgument","name":"repoOwner","type":"String!","defaultValue":null},{"kind":"LocalArgument","name":"repoName","type":"String!","defaultValue":null},{"kind":"LocalArgument","name":"branchName","type":"String!","defaultValue":null}],"kind":"Root","name":"PrInfoControllerByBranchQuery","operation":"query","selections":[{"kind":"LinkedField","alias":null,"args":[{"kind":"Variable","name":"name","variableName":"repoName","type":"String!"},{"kind":"Variable","name":"owner","variableName":"repoOwner","type":"String!"}],"concreteType":"Repository","name":"repository","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":[{"kind":"Literal","name":"first","value":30,"type":"Int"},{"kind":"Variable","name":"headRefName","variableName":"branchName","type":"String"}],"concreteType":"PullRequestConnection","name":"pullRequests","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"totalCount","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"PullRequestEdge","name":"edges","plural":true,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"PullRequest","name":"node","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"createdAt","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"title","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"url","storageKey":null},{"kind":"LinkedField","alias":null,"args":[{"kind":"Literal","name":"last","value":1,"type":"Int"}],"concreteType":"PullRequestCommitConnection","name":"commits","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"PullRequestCommitEdge","name":"edges","plural":true,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"PullRequestCommit","name":"node","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"Commit","name":"commit","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"Status","name":"status","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"state","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"StatusContext","name":"contexts","plural":true,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"state","storageKey":null},{"kind":"InlineFragment","type":"StatusContext","selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"context","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"description","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"targetUrl","storageKey":null}]}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null}],"storageKey":null}],"storageKey":"commits{\"last\":1}"},{"kind":"ScalarField","alias":null,"args":null,"name":"state","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"number","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":null,"name":"author","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"__typename","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"login","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"avatarUrl","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null},{"kind":"InlineFragment","type":"Bot","selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"url","storageKey":null}]},{"kind":"InlineFragment","type":"User","selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"url","storageKey":null}]}],"storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"Repository","name":"repository","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"name","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":null,"name":"owner","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"__typename","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"login","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"ReactionGroup","name":"reactionGroups","plural":true,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"content","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"ReactingUserConnection","name":"users","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"totalCount","storageKey":null}],"storageKey":null}],"storageKey":null},{"kind":"LinkedField","alias":"commitsCount","args":null,"concreteType":"PullRequestCommitConnection","name":"commits","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"totalCount","storageKey":null}],"storageKey":null},{"kind":"LinkedField","alias":null,"args":[{"kind":"Literal","name":"first","value":100,"type":"Int"}],"concreteType":"LabelConnection","name":"labels","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"LabelEdge","name":"edges","plural":true,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"Label","name":"node","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"name","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"color","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null}],"storageKey":null}],"storageKey":"labels{\"first\":100}"}],"storageKey":null}],"storageKey":null}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null}]},"text":"query PrInfoControllerByBranchQuery(\n $repoOwner: String!\n $repoName: String!\n $branchName: String!\n) {\n repository(owner: $repoOwner, name: $repoName) {\n ...PrSelectionByBranchContainer_repository\n id\n }\n}\n\nfragment PrSelectionByBranchContainer_repository on Repository {\n pullRequests(first: 30, headRefName: $branchName) {\n totalCount\n edges {\n node {\n id\n number\n title\n url\n ...PrInfoContainer_pullRequest\n }\n }\n }\n}\n\nfragment PrInfoContainer_pullRequest on PullRequest {\n ...PrStatusesContainer_pullRequest\n id\n url\n number\n title\n state\n createdAt\n author {\n __typename\n login\n avatarUrl\n ... on User {\n url\n }\n ... on Bot {\n url\n }\n ... on Node {\n id\n }\n }\n repository {\n name\n owner {\n __typename\n login\n id\n }\n id\n }\n reactionGroups {\n content\n users {\n totalCount\n }\n }\n commitsCount: commits {\n totalCount\n }\n labels(first: 100) {\n edges {\n node {\n name\n color\n id\n }\n }\n }\n}\n\nfragment PrStatusesContainer_pullRequest on PullRequest {\n id\n commits(last: 1) {\n edges {\n node {\n commit {\n status {\n state\n contexts {\n id\n state\n ...PrStatusContextContainer_context\n }\n id\n }\n id\n }\n id\n }\n }\n }\n}\n\nfragment PrStatusContextContainer_context on StatusContext {\n context\n description\n state\n targetUrl\n}\n"}.
`
in
`/Applications/Atom.app/Contents/Resources/app/node_modules/fbjs/lib/invariant.js:49
`

### Steps to Reproduce

1. toggle github tab
2. get authorization token from https://github.atom.io/auth/github_package/token
3. click on login button

**Expected behavior:**

let me login to github

**Actual behavior:**

no response no matter when I click on the login button

**Reproduces how often:**

[What percentage of the time does this happen?]

### Versions

apm  1.18.12
npm  3.10.10
MacOS 10.13.3

### Additional Information

I can use git via atom without any error before atom updates to 1.24.1. 

If your issue involves a repository, and that repository is public, please include a link to it.

**Comment by smashwilson** [comment] 2018-03-11 15:40
Duplicate of #1340, and fixed in #1344. 😄

**Closed by smashwilson** 2018-03-11 15:40 UTC

**Comment by import-antigravity** [comment] 2018-03-14 04:28
I have version 1.24.1 and it's still not working...

**Comment by smashwilson** [comment] 2018-03-14 12:46
That's expected, unfortunately - the fix will ship with Atom 1.25 and 1.26-beta0.

**Comment by oba2311** [comment] 2019-06-30 19:52
Still experiencing the same issue with 1.38 on MacOS HighSierra (10.13)

**Comment by itskaty** [comment] 2020-09-03 01:51
Experiencing this issue with Atom 1.50.0 Windows 10 Pro X64

**Comment by Alterraia** [comment] 2020-11-10 21:03
Experiencing it  it with 1.53.0 Windows 10.  I was in it not even 12 hours ago from this post, and I got on my PC today and I can't do anything.  And please no more redirecting us to another post with many comments, but no solution.  I feel like I've been going in circles.

I enter my username and email address, continue button is useless.

I revoked access, got a new token, nowhere to put it.  This shouldn't be an issue.

The only thing I did last night was make a 2nd repository that I did not link to anything as it doesn't need to be linked to atom.  But I can do exactly nothing now, and it seems this issue keeps coming back and is never fully resolved.

I've seen instances in say, video games, where something is broken, it's patched, but then it breaks again as the problematic coding just wasn't fixed in the first place.

**Comment by opus-x** [comment] 2021-05-22 08:06
Still not fixed in v1.57.0. 

+1 @Alterraia

**Comment by rakitadragan** [comment] 2021-07-01 11:22
I have this problem in v1.57.0 on Linux.

**Comment by ginstagram** [comment] 2022-01-21 08:47
The problem still persists in v1.58.0 on MacOS. Can it be an inability to use GitHub and GitLab at the same time?

**Comment by vonstegen** [comment] 2022-05-20 16:07
Still the same issue with v1.59.0 on MacOS Monterey

For all those looking for the solution to this issue

**Comment by mdlinville** [comment] 2022-06-07 17:20
Me too ✋ Atom 1.60, macOS 12.4. @smashwilson Can you reopen this based on the comments after you said it was fixed?

**Comment by TheR0cketMan** [comment] 2022-09-07 23:38
Still having this issue on Linux v1.60.0
