### ISSUE TITLE
Improve the startup time

### ISSUE THREAD

**Issue by mittalyashu** [atom/github#1258] opened 2017-11-19 13:51 UTC
![image](https://user-images.githubusercontent.com/29014463/32991307-c9cc85f6-cd5e-11e7-925e-0bf4d0a94626.png)

**Comment by serafeimgr** [comment] 2017-11-29 20:10
I have also raised this in #920

**Comment by rsese** [comment] 2017-11-30 18:29
Thanks @serafeimgr, we'll go ahead and close as a duplicate of https://github.com/atom/github/issues/920.  You can share your screenshot and other details in that issue @mittalyashu.

**Closed by rsese** 2017-11-30 18:29 UTC
