### ISSUE TITLE
Status-bar push-pull button has click listener on text instead of div

### ISSUE THREAD

**Issue by Flying-Toast** [atom/github#1606] opened 2018-07-23 02:08 UTC
The git push/pull/fetch button in the status-bar only works if you click on the text inside the button -- not if you click the background of the div, unlike the other status-bar buttons. 
I would like to try and fix this bug myself, but I am confused by how to do that.
Could someone give me a little guidance on how to go about fixing this? I would really appreciate it. :smile:

**Comment by simurai** [comment] 2018-07-23 03:39
This sounds like a duplicate of #1530 and should already be fixed with #1534, but thanks for wanting to fix it. ❤️ 🙇

**Closed by simurai** 2018-07-23 03:39 UTC
