### ISSUE TITLE
Github package doesn't remember my login and password between transactions

### ISSUE THREAD

**Issue by adrian3H** [atom/github#897] opened 2017-06-01 04:15 UTC
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]?
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?
* Have you checked the FAQs on the [message board][message-board] for common solutions?
* Have you checked that your issue [isn't already filed][already-filed]?

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:**

[What did you expect to happen?]

**Actual behavior:**

[What actually happened instead?]

**Reproduces how often:**

[What percentage of the time does this happen?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Please include any additional information, configuration or data that might be necessary to reproduce the issue. Screenshots, if appropriate, are helpful as well.

If your issue involves a repository, and that repository is public, please include a link to it.

**Comment by BinaryMuse** [comment] 2017-06-01 05:38
This appears to be a duplicate of https://github.com/atom/github/issues/861.

As a side note, we require the template to be filled out on all new issues and pull requests so please fill it out completely in the future for new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Closed by BinaryMuse** 2017-06-01 05:38 UTC
