### ISSUE TITLE
Display reviews inside the pull request pane

### ISSUE THREAD

**Issue by npezza93** [atom/github#1623] opened 2018-08-01 03:17 UTC
### Description

When opening a PR, show reviews inside the PR pane. Regular comments show perfectly but reviews don't show. 

### Steps to Reproduce

1. Open a PR that has been reviewed and has regular comments.
2. The regular comments show up but the review approvals/change requests/comments do not show.

**Expected behavior:**

All reviews to display just like comments currently do.

**Actual behavior:**

Reviews do not show but regular comments do.

**Reproduces how often:**

100%

### Versions

1.30.0-beta1

**Comment by rsese** [comment] 2018-08-03 03:51
Thanks for the suggestion!

This looks like a duplicate of https://github.com/atom/github/issues/268 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-08-03 03:51 UTC
