### ISSUE TITLE
Github sets git global user.email to repo's local user.email

### ISSUE THREAD

**Issue by beingmrkenny** [atom/github#2628] opened 2021-02-18 14:10 UTC
### Description

I use git at work where the global `~/.gitconfig` has a `user.email` of, let's say, work@example.com.

I also use a personal github repo with all my dotfiles where all commits need a `user.email` of, let's say home@example.com. I have set the `/repo/.git/config` in this repo to a `user.email` of home@example.com.

I find when I open this repo in atom, with github enabled, it resets my _global_ `user.email` to home@example.com, which is a huge inconvenience since I have to manually change it back every time I open this local repo.

When github is disabled, this doesn't happen.

### Steps to Reproduce

1. Set your global `user.email` to one email address with `git config --global user.email work@example.com`
2. Set the local `user.email` to a different email address when the working dir is that repo with `git config user.email home@example.com`
3. Open the repo with `atom .`
4. View your global .gitconfig with `less ~/.gitconfig` — the user.email will now be home@example.com.

**Expected behavior:**

There should be no change to the global .gitconfig, regardless of what the repo's git config is set to

**Actual behavior:**

Global git config user.email is changed

**Reproduces how often:**

100%

### Versions

github 0.36.2

Atom    : 1.54.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0

apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.54.0
python 2.7.15
git 2.29.2

macOS 10.15.7

**Comment by smashwilson** [comment] 2021-02-18 16:53
Duplicate of #2622 and #2557 and probably a few others that I can't find right now. Already fixed by #2587. The latest package version lets you choose explicitly:

![image](https://user-images.githubusercontent.com/17565/107086387-ee5a9a00-67c7-11eb-9199-07aaed60a72b.png)

Try switching to [Atom Nightly](https://atom.io/nightly) if you want this behavior sooner rather than later!

**Closed by smashwilson** 2021-02-18 16:53 UTC

**Comment by beingmrkenny** [comment] 2021-02-18 18:41
@smashwilson Ah that's great news, this has been happening for a while now :) Any estimate as to when atom might release this?
