### ISSUE TITLE
Git for Atom not working v1.21.0

### ISSUE THREAD

**Issue by b4dnewz** [atom/github#1201] opened 2017-10-05 12:05 UTC
I've installed atom few times on my Windows machine from the official website which right now send the **version 1.21.0** and I would like to use the new **Git/Github integration for Atom** which should be built in the core on versions up to 1.18.x as the site says: https://github.atom.io/

But I don't see it, neither I see an option to enable it.

On my linux machine I've atom stable (v1.20.1) and it's enabled but here I can't make it work, am I missing something?

Anybody has the same problem?

**Comment by the-j0k3r** [comment] 2017-10-07 16:09
Have you tried `Ctrl+Shift+9` and `Ctrl+Shift+8`

![capture](https://user-images.githubusercontent.com/31389848/31309676-272d3910-ab82-11e7-9eb5-1db19890ec70.PNG)

Works around here, its buggy as hell but it shows up.

**Comment by b4dnewz** [comment] 2017-10-07 16:22
I've just tried but when I click (or use the keyboard shortcut) nothing is shown and no errors in the console, lol.

**Comment by the-j0k3r** [comment] 2017-10-07 16:26
What version of Windows do you have exactly? Is it 32-bit 64-bit?

Works fine here on windows 10 pro 64-bit at least.

**Comment by b4dnewz** [comment] 2017-10-07 16:28
windows 10 pro 64bit like yours and I've installed Atom stable two days ago, before I was using the beta version and even there wasn't working that feature.

**Comment by the-j0k3r** [comment] 2017-10-07 16:30
Try to on a different user profile... Its there I promise :) its buggy but its there.

**Comment by b4dnewz** [comment] 2017-10-07 16:42
I've already wiped out few times the .atom stuff in my profile in attempt to resolve this previously, right now it's not a big deal (if is not working) but I'll still try to debug it, do you know under which path this core package should be available?

Im looking here and subs folder: `C:\Users\MYUSER\AppData\Local\atom\app-1.21.0`

**Comment by the-j0k3r** [comment] 2017-10-07 17:03
Maybe one of the crew can help you but its really buggy, its a catch 22.

**Comment by smashwilson** [comment] 2017-10-08 14:41
That's odd. If the package failed to activate, you should have a stack trace in your console.

Are the status bar tiles showing up? It should look like this:

<img width="160" alt="status-bar" src="https://user-images.githubusercontent.com/17565/31317716-04c4b258-ac14-11e7-9da3-1db67ee963d8.PNG">

If so: try running `Window: Open Right Dock` from the command palette. I'm not sure why the dock toggling API wouldn't be working though 🤔

**Comment by b4dnewz** [comment] 2017-10-08 14:49
@smashwilson I don't see the status bar and after I manually reloaded atom instance with the inspector opened the stack trace shows this:
```bash
Uncaught (in promise) TypeError: validateDOMNesting.updatedAncestorInfo is not a function
    at ReactDOMContainerInfo (C:\Users\USERNAME\AppData\Local\atom\app-1.21.0\resources\app\node_modules\react-dom\lib\ReactDOMContainerInfo.js:25:58)
    at mountComponentIntoNode (C:\Users\USERNAME\AppData\Local\atom\app-1.21.0\resources\app\node_modules\react-dom\lib\ReactMount.js:102:89)
    at ReactReconcileTransaction.perform (C:\Users\USERNAME\AppData\Local\atom\app-1.21.0\resources\app\node_modules\react-dom\lib\Transaction.js:141:26)
    at batchedMountComponentIntoNode (C:\Users\USERNAME\AppData\Local\atom\app-1.21.0\resources\app\node_modules\react-dom\lib\ReactMount.js:124:21)
    at ReactDefaultBatchingStrategyTransaction.perform (C:\Users\USERNAME\AppData\Local\atom\app-1.21.0\resources\app\node_modules\react-dom\lib\Transaction.js:141:26)
    at Object.batchedUpdates (C:\Users\USERNAME\AppData\Local\atom\app-1.21.0\resources\app\node_modules\react-dom\lib\ReactDefaultBatchingStrategy.js:60:32)
    at Object.batchedUpdates (C:\Users\USERNAME\AppData\Local\atom\app-1.21.0\resources\app\node_modules\react-dom\lib\ReactUpdates.js:95:33)
    at Object._renderNewRootComponent (C:\Users\USERNAME\AppData\Local\atom\app-1.21.0\resources\app\node_modules\react-dom\lib\ReactMount.js:317:24)
    at Object._renderSubtreeIntoContainer (C:\Users\USERNAME\AppData\Local\atom\app-1.21.0\resources\app\node_modules\react-dom\lib\ReactMount.js:399:38)
    at Object.render (C:\Users\USERNAME\AppData\Local\atom\app-1.21.0\resources\app\node_modules\react-dom\lib\ReactMount.js:420:29)
    at GithubPackage.rerender (C:\Users\USERNAME\AppData\Local\atom\app-1.21.0\resources\app\node_modules\github\lib\github-package.js:336:30)
    at C:\Users\USERNAME\AppData\Local\atom\app-1.21.0\resources\app\node_modules\github\lib\github-package.js:305:19
    at Generator.next (<anonymous>)
    at step (C:\Users\USERNAME\AppData\Local\atom\app-1.21.0\resources\app\node_modules\github\lib\github-package.js:96:197)
    at C:\Users\USERNAME\AppData\Local\atom\app-1.21.0\resources\app\node_modules\github\lib\github-package.js:96:367
ReactDOMContainerInfo @ <embedded>:275552
mountComponentIntoNode @ <embedded>:222614
perform @ <embedded>:276649
batchedMountComponentIntoNode @ <embedded>:222636
perform @ <embedded>:276649
batchedUpdates @ <embedded>:274003
batchedUpdates @ <embedded>:223309
_renderNewRootComponent @ <embedded>:222829
_renderSubtreeIntoContainer @ <embedded>:222911
render @ <embedded>:222932
rerender @ <embedded>:48924
(anonymous) @ <embedded>:48893
step @ <embedded>:48684
(anonymous) @ <embedded>:48684
internal/process/next_tick.js:103 Uncaught (in promise) TypeError: validateDOMNesting.updatedAncestorInfo is not a function
    at ReactDOMContainerInfo (C:\Users\USERNAME\AppData\Local\atom\app-1.21.0\resources\app\node_modules\react-dom\lib\ReactDOMContainerInfo.js:25:58)
    at mountComponentIntoNode (C:\Users\USERNAME\AppData\Local\atom\app-1.21.0\resources\app\node_modules\react-dom\lib\ReactMount.js:102:89)
    at ReactReconcileTransaction.perform (C:\Users\USERNAME\AppData\Local\atom\app-1.21.0\resources\app\node_modules\react-dom\lib\Transaction.js:141:26)
    at batchedMountComponentIntoNode (C:\Users\USERNAME\AppData\Local\atom\app-1.21.0\resources\app\node_modules\react-dom\lib\ReactMount.js:124:21)
    at ReactDefaultBatchingStrategyTransaction.perform (C:\Users\USERNAME\AppData\Local\atom\app-1.21.0\resources\app\node_modules\react-dom\lib\Transaction.js:141:26)
    at Object.batchedUpdates (C:\Users\USERNAME\AppData\Local\atom\app-1.21.0\resources\app\node_modules\react-dom\lib\ReactDefaultBatchingStrategy.js:60:32)
    at Object.batchedUpdates (C:\Users\USERNAME\AppData\Local\atom\app-1.21.0\resources\app\node_modules\react-dom\lib\ReactUpdates.js:95:33)
    at Object._renderNewRootComponent (C:\Users\USERNAME\AppData\Local\atom\app-1.21.0\resources\app\node_modules\react-dom\lib\ReactMount.js:317:24)
    at Object._renderSubtreeIntoContainer (C:\Users\USERNAME\AppData\Local\atom\app-1.21.0\resources\app\node_modules\react-dom\lib\ReactMount.js:399:38)
    at Object.render (C:\Users\USERNAME\AppData\Local\atom\app-1.21.0\resources\app\node_modules\react-dom\lib\ReactMount.js:420:29)
    at GithubPackage.rerender (C:\Users\USERNAME\AppData\Local\atom\app-1.21.0\resources\app\node_modules\github\lib\github-package.js:336:30)
    at GithubPackage.setActiveContext (C:\Users\USERNAME\AppData\Local\atom\app-1.21.0\resources\app\node_modules\github\lib\github-package.js:633:18)
    at C:\Users\USERNAME\AppData\Local\atom\app-1.21.0\resources\app\node_modules\github\lib\github-package.js:654:20
    at Generator.next (<anonymous>)
    at step (C:\Users\USERNAME\AppData\Local\atom\app-1.21.0\resources\app\node_modules\github\lib\github-package.js:96:197)
    at C:\Users\USERNAME\AppData\Local\atom\app-1.21.0\resources\app\node_modules\github\lib\github-package.js:96:367
    at process._tickCallback (internal/process/next_tick.js:103:7)
ReactDOMContainerInfo @ <embedded>:275552
mountComponentIntoNode @ <embedded>:222614
perform @ <embedded>:276649
batchedMountComponentIntoNode @ <embedded>:222636
perform @ <embedded>:276649
batchedUpdates @ <embedded>:274003
batchedUpdates @ <embedded>:223309
_renderNewRootComponent @ <embedded>:222829
_renderSubtreeIntoContainer @ <embedded>:222911
render @ <embedded>:222932
rerender @ <embedded>:48924
setActiveContext @ <embedded>:49221
(anonymous) @ <embedded>:49242
step @ <embedded>:48684
(anonymous) @ <embedded>:48684
_tickCallback @ internal/process/next_tick.js:103
C:\Users\USERNAME\.atom\packages\linter-ui-default\node_modules\react-dom\lib\ReactDOM.js:71 Download the React DevTools and use an HTTP server (instead of a file: URL) for a better development experience: https://fb.me/react-devtools
```

There I see this: `at GithubPackage.rerender (C:\Users\USERNAME\AppData\Local\atom\app-1.21.0\resources\app\node_modules\github\lib\github-package.js:336:30)` I didn't noticed before, there was a bunch of errors and I didn't filter the right way.

Thanks for helping me to fix this.

**Comment by smashwilson** [comment] 2017-10-08 15:27
@b4dnewz Do you by any chance have `NODE_ENV` set to "development"? You can check by running this in the dev tools:

```
process.env.NODE_ENV
```

If so, this looks like a duplicate of #833. A quick fix is to quit and re-launch Atom with `NODE_ENV` unset or set to "production".

**Closed** 2017-10-08 15:42 UTC
