### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dispatchEvent' of null

### ISSUE THREAD

**Issue by Nerwosolek** [atom/github#1070] opened 2017-08-01 12:05 UTC
[Enter steps to reproduce:]

1. clicking files in status bar on the bottom
2. clicking one of files in the unstaged changes area.
Atom hangs for a long time and then throws exception

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [github](https://github.com/atom/github) package 0.3.3

### Stack Trace

Uncaught TypeError: Cannot read property 'dispatchEvent' of null

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/github/lib/views/staging-view.js:477

TypeError: Cannot read property 'dispatchEvent' of null
    at /Applications/Atom.app/Contents/Resources/app/node_modules/github/lib/views/staging-view.js:477:40
```

### Commands

```
```

### Non-Core Packages

```
angularjs 0.4.0 
atom-html-preview 0.1.22 
atom-minify 0.8.0 
autocomplete-angular-material 0.4.0 
autocomplete-python 1.9.1 
busy-signal 1.4.3 
dash 1.7.1 
intentions 1.1.2 
linter 2.2.0 
linter-js-standard 3.9.1 
linter-jshint 3.1.5 
linter-ui-default 1.6.2 
pigments 0.39.1 
```

**Comment by rsese** [comment] 2017-08-08 20:25
Thanks for the report!  Can you confirm if the error is reproducible and if so, is it reproducible in safe mode (atom --safe)?

Also, do you see this behavior for any repository (e.g. a simple test repo) or just a particular one?

**Comment by Nerwosolek** [comment] 2017-08-17 16:32
I cannot reproduce it for now.

**Comment by rsese** [comment] 2017-08-17 21:00
Thanks for letting us know :+1:  We'll close it for now since it's not reproducible but we can always re-open if you start hitting it again.

**Closed by rsese** 2017-08-17 21:00 UTC
Labels: more-information-needed, uncaught-exception
