### ISSUE TITLE
Diif view autoscrolls back to where it was when trying to manually scroll it

### ISSUE THREAD

**Issue by ricardograca** [atom/github#1301] opened 2018-02-02 19:08 UTC
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]? Yes
* Have you followed all applicable steps in the [debugging guide][debugging-guide]? Most
* Have you checked the FAQs on the [message board][message-board] for common solutions? Yes
* Have you checked that your issue [isn't already filed][already-filed]? Yes

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

Whenever I try to manually scroll the diff view window it auto-scrolls back to where it was before. This only happens if I use the mouse to move the scrollbar. If I use the mouse scroll wheel or Page Up/Down to scroll the view then everything works as expected.

### Steps to Reproduce

1. Click on a file with a diff longer than a single page
2. Point to the scrollbar, click and hold
3. Move the mouse up or down so that the view changes accordingly
4. Let go of mouse button

**Expected behavior:**

The view stays where it was when I let go of the mouse button.

**Actual behavior:**

The view scrolled itself back to the starting point (step 2 above).

**Reproduces how often:**

100%

### Versions

Atom    : 1.23.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

This is on Ubuntu 16.04.3 with all the latest updates.

### Additional Information

![gifrecord_2018-02-02_185011](https://user-images.githubusercontent.com/1457035/35750145-f1da4588-084b-11e8-845c-413d4083c226.gif)

In the gif above the mouse cursor isn't visible, but the first time the image scrolls down I was doing that, and you can see it going back to the beginning when letting go of the mouse button.

**Comment by Arcanemagus** [comment] 2018-02-02 19:42
Should be fixed by https://github.com/atom/github/pull/1281 which hasn't been released yet.

Duplicate of https://github.com/atom/github/issues/1226 / related to https://github.com/atom/github/issues/884.

**Closed** 2018-02-02 20:06 UTC
