### ISSUE TITLE
Highlight line differences in Unstaged/Staged Changes's Diff

### ISSUE THREAD

**Issue by germanocorrea** [atom/github#1271] opened 2018-01-04 12:13 UTC
* **Have you checked that your issue [isn't already filed][already-filed]?** I haven't found any related issues.

It would be a helpful feature if, in unstaged and staged changes, the diff view could highlight the differences between lines, like this GitHub's diff print screen:

![screenshot-2018-1-4 fixed board grid and columns alignment germanocorrea waddle b8aab79](https://user-images.githubusercontent.com/9283794/34562885-710ae654-f137-11e7-9354-9556889b642c.png)

It's easier to review code before a commit, what is removed, what is added, not only entire lines.

**Comment by Arcanemagus** [comment] 2018-01-04 18:26
Duplicate of https://github.com/atom/github/issues/759.

**Comment by rsese** [comment] 2018-01-04 19:40
Thanks @Arcanemagus :v:  You can subscribe to #759 for updates if you'd like @germanocorrea.

**Closed by rsese** 2018-01-04 19:40 UTC

**Comment by germanocorrea** [comment] 2018-01-05 10:30
Thanks @Arcanemagus, I must have not paid attention when searching for similar issues.

Sorry about the duplicate.
