### ISSUE TITLE
File opens on right instead in Editor pane in atom git tab

### ISSUE THREAD

**Issue by sombhotlu** [atom/github#1270] opened 2017-12-28 04:56 UTC
### Description
Single click on a file name of git tab should open a file on editor pane on left instead of right in that small window.

### Versions

Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

### Additional Information
![Before Clicking on a file](https://user-images.githubusercontent.com/17179776/34400739-48caf166-ebba-11e7-9242-4b2cf065243f.jpg)
![After clicking on a file](https://user-images.githubusercontent.com/17179776/34400740-4b9833ea-ebba-11e7-8b5b-bd0f80ff0c0f.jpg)

**Comment by rsese** [comment] 2017-12-29 05:24
Thanks for the report!  Can you update to the latest stable release version (currently 1.23.1) and let us know if this is still reproducible for you?  And can you also confirm if it's reproducible in safe mode (`atom --safe`)?

**Comment by sombhotlu** [comment] 2017-12-29 10:15
Thankyou very much after closing and reopening the project folder showed different panes in atom which were hidden earlier. When I removed all the unnecessary panes it worked perfectly. Is there any shortcut to view number of panes at once ?

**Comment by bennypowers** [comment] 2018-04-11 11:09
Somewhat related: a workflow I often use is to vertically split the editor window into editors on the left and utilities (project find, unstaged changes, terminal, etc) on the right. Now if I am exploring a diff in the right pane and press `o` to open the file, the file will open in the right pane. I would like to be able to designate the right pane for unstaged changes, and have files open in the left pane.

**Comment by rsese** [comment] 2018-04-11 18:04
> Thankyou very much after closing and reopening the project folder showed different panes in atom which were hidden earlier. When I removed all the unnecessary panes it worked perfectly.

Sorry I missed your followup @sombhotlu, glad that things seem sorted out now.  I'll go ahead and close the issue since your original issue is resolved.

> Is there any shortcut to view number of panes at once ?

Can you clarify what you mean here?  Does `Fuzzy Finder: Toggle Buffer Finder` help?

> Somewhat related: a workflow I often use is to vertically split the editor window into editors on the left and utilities (project find, unstaged changes, terminal, etc) on the right. Now if I am exploring a diff in the right pane and press o to open the file, the file will open in the right pane. I would like to be able to designate the right pane for unstaged changes, and have files open in the left pane.

Thanks for the feedback @bennypowers - since this issue was more of a bug report and we're closing it since it's resolved, feel free to open a new issue with your feedback.  If you can use the issue template as much as possible, that's helpful for us as well.

**Closed by rsese** 2018-04-11 18:04 UTC
Labels: more-information-needed
