### ISSUE TITLE
Uncaught Error: ~/Desktop\test.html does not belong to repo null

### ISSUE THREAD

**Issue by chenyang3411** [atom/github#992] opened 2017-06-28 02:36 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [github](https://github.com/atom/github) package 0.3.3

### Stack Trace

Uncaught Error: C:\Users\Ryo\Desktop\test.html does not belong to repo null

```
At C:\Users\Ryo\AppData\Local\atom\app-1.18.0\resources\app\node_modules\github\lib\controllers\root-controller.js:807

Error: C:\Users\Ryo\Desktop\test.html does not belong to repo null
    at RootController.viewChangesForCurrentFile (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/github/lib/controllers/root-controller.js:807:19)
    at RootController.viewUnstagedChangesForCurrentFile (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/github/lib/controllers/root-controller.js:812:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.18.0/resources/app/src/atom-environment.js:1320:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.18.0/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:26.8.0 atom-beautify:beautify-editor (div.)
     -1:00.7.0 github:view-unstaged-changes-for-current-file (div.line)
     -0:16.9.0 atom-beautify:beautify-editor (div.line)
```

### Non-Core Packages

```
atom-beautify 0.30.3 
atom-minify 0.8.0 
autocomplete-paths 1.0.5 
css-snippets 1.1.0 
highlight-selected 0.13.1 
language-vue 0.23.0 
language-vue-component 0.5.0 
less-autocompile 1.0.0 
tortoise-svn 0.5.1 
vue2-autocomplete 0.1.0-alpha.4 
```

**Comment by rsese** [comment] 2017-06-28 04:19
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/github/issues/950. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-06-28 04:19 UTC
