### ISSUE TITLE
Can't initialize remote github repo from new atom project.

### ISSUE THREAD

**Issue by orange-thunder** [atom/github#2633] opened 2021-02-28 11:53 UTC
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Can't connect completely new project to github. Can't initialize a repository from it. The button is greyed out, the path is stuck in "loading" state.

### Steps to Reproduce

1. Open a new project
2. Attempt to initialize a new remote repo from it
3. The button is greyed out. That's it. And I can't seem to understand why

**Expected behavior:**

To create it normally. It should be pretty straight-forward but my Atom just won't let me do it.

**Actual behavior:**

I can't create the remote repo in my github account.

**Reproduces how often:**

100% of the time. I've never managed to open a github repository from atom.

### Versions

Atom --> 1.5.4
Windows 10

### Additional Information

![image](https://user-images.githubusercontent.com/72664651/109417320-68470300-79c3-11eb-91c3-73e2c0313cfc.png)
(there's a "forbidden" sign when i hover the "Publish" button)

**Comment by smashwilson** [comment] 2021-02-28 15:30
Duplicate of #2542 and #2616. Partially fixed by https://github.com/atom/github/pull/2572 (which will correctly show you a login prompt instead of the "create" or "publish" buttons when you're logged out) which is currently available on [Atom Nightly](https://atom.io/nightly) and will be included in the next stable Atom release.

**Closed by smashwilson** 2021-02-28 15:30 UTC
