### ISSUE TITLE
Add option to hide the 'Undo discard' button [feature-request]

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [atom/github#1296] opened 2018-01-27 10:45 UTC
I don't know if it's only me, but from time to time I press the 'Undo discard' button by mistake while trying to click on the first modified file on the right pane.

It would be very nice to have an option in the settings to hide that button.

**Comment by Arcanemagus** [comment] 2018-01-28 00:50
Come join the party in #605 of all of us that want this button removed 😉.

**Comment by Ben3eeE** [comment] 2018-01-29 10:49
Thanks @Arcanemagus :bowing_man: 

This is a duplicate of #605 

---

Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/github/issues/605. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2018-01-29 10:49 UTC
Labels: duplicate
