### ISSUE TITLE
sub folder as repositories

### ISSUE THREAD

**Issue by jpujari-cartera** [atom/github#2176] opened 2019-06-04 16:59 UTC
I am using the tree-view-git-status plugin. It doesn't work for subfolders within the project folder. As per the plugin team, it is because atom doesn't recognize subfolder as git repos. Can we make this happen? will be really useful. You can read the plugin team's response in the following issue.

https://github.com/subesokun/atom-tree-view-git-status/issues/35

**Comment by rsese** [comment] 2019-06-05 01:59
Thanks for reaching out - this is a duplicate of https://github.com/atom/github/issues/1835 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-06-05 01:59 UTC
