### ISSUE TITLE
Uncaught Error: D:/qingang\study\src\main.jsx does not belong to repo null

### ISSUE THREAD

**Issue by qingang771920524** [atom/github#1088] opened 2017-08-08 08:45 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [github](https://github.com/atom/github) package 0.3.3

### Stack Trace

Uncaught Error: D:\qingang\study\src\main.jsx does not belong to repo null

```
At D:\Users\mingrui\AppData\Local\atom\app-1.18.0\resources\app\node_modules\github\lib\controllers\root-controller.js:807

Error: D:\qingang\study\src\main.jsx does not belong to repo null
    at RootController.viewChangesForCurrentFile (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/github/lib/controllers/root-controller.js:807:19)
    at RootController.viewUnstagedChangesForCurrentFile (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/github/lib/controllers/root-controller.js:812:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.18.0/resources/app/src/atom-environment.js:1320:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.18.0/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -5:19.7.0 intentions:highlight (input.hidden-input)
     -5:19.5.0 core:select-all (input.hidden-input)
     -5:10 github:view-unstaged-changes-for-current-file (div.)
     -4:53.6.0 core:backspace (input.hidden-input)
     -4:52.6.0 intentions:highlight (input.hidden-input)
     -4:52.4.0 core:save (input.hidden-input)
     -4:50.1.0 github:view-unstaged-changes-for-current-file (div.line)
     -4:43.4.0 intentions:highlight (input.hidden-input)
     -4:43.2.0 core:save (input.hidden-input)
     -4:40.1.0 atom-beautify:help-debug-editor (div.line)
     -4:29.8.0 github:view-staged-changes-for-current-file (div.line.cursor-line)
     -1:50.5.0 spell-check:correct-misspelling (div.line)
     -1:41 github:view-staged-changes-for-current-file (div.lines)
     -0:57.2.0 tree-view:move (div.tool-panel.tree-view)
     -0:55 core:confirm (input.hidden-input)
     -0:45.3.0 github:view-unstaged-changes-for-current-file (div.line)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-react-autocomplete 0.1.10 
atom-ternjs 0.18.3 
autocomplete 0.47.0 
autocomplete-js-import 1.4.0 
autocomplete-modules 1.6.10 
autocomplete-paths 1.0.5 
busy-signal 1.4.3 
color-picker 2.2.5 
docblockr 0.11.0 
editorconfig 2.2.2 
emmet 2.4.3 
emmet-jsx-css-modules 1.0.0 
file-icons 2.1.10 
git-plus 7.9.3 
highlight-selected 0.13.1 
hyperclick 0.1.3 
intentions 1.1.5 
js-func-viewer 1.1.4 
js-hyperclick 1.11.0 
language-babel 2.69.0 
language-javascript-jsx 0.3.7 
language-postcss 1.3.1 
linter 2.2.0 
linter-eslint 8.2.1 
linter-jshint 3.1.5 
linter-ui-default 1.6.3 
merge-conflicts 1.4.5 
minimap 4.29.3 
project-manager 3.3.5 
react-es6-snippets 0.3.0 
react-es7-snippets 0.3.13 
react-snippets 0.9.0 
travis-ci-status 1.3.1 
```

**Comment by BinaryMuse** [comment] 2017-08-08 16:24
Duplicate of https://github.com/atom/github/issues/950

**Closed by BinaryMuse** 2017-08-08 16:24 UTC
