### ISSUE TITLE
Strange Output about `scl`

### ISSUE THREAD

**Issue by TJProgrammer** [atom/github#2397] opened 2020-01-27 00:57 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

A strange output about `scl` appears.

### Steps to Reproduce

1. Make a modification
2. Try to push it, but with wrong password.
3. Get the error (see the image).

**Expected behavior:**

No strange output.

**Actual behavior:**

A strange output (see the image).
![Captura de ecrã de 2020-01-27 00-46-13](https://user-images.githubusercontent.com/7900361/73144661-e1c54100-409f-11ea-8809-5664791e9c37.png)

**Reproduces how often:**

Always.

### Versions

Fedora 31 Wayland

Atom    : 1.43.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0

apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.43.0
python 3.7.6
git 2.24.1

### Additional Information

See: https://github.com/atom/atom/issues/13451

The all output:

```
Unable to push

/bin/sh: module: linha 1: erro de sintaxe: fim de ficheiro inesperado
/bin/sh: erro ao importar definição de função para "module"
/bin/sh: scl: linha 1: erro de sintaxe: fim de ficheiro inesperado
/bin/sh: erro ao importar definição de função para "scl"
/bin/sh: switchml: linha 1: erro de sintaxe: fim de ficheiro inesperado
/bin/sh: erro ao importar definição de função para "switchml"
/bin/sh: module: linha 1: erro de sintaxe: fim de ficheiro inesperado
/bin/sh: erro ao importar definição de função para "module"
/bin/sh: scl: linha 1: erro de sintaxe: fim de ficheiro inesperado
/bin/sh: erro ao importar definição de função para "scl"
/bin/sh: switchml: linha 1: erro de sintaxe: fim de ficheiro inesperado
/bin/sh: erro ao importar definição de função para "switchml"
/bin/sh: switchml: linha 1: erro de sintaxe: fim de ficheiro inesperado
/bin/sh: erro ao importar definição de função para "switchml"
/bin/sh: module: linha 1: erro de sintaxe: fim de ficheiro inesperado
/bin/sh: erro ao importar definição de função para "module"
/bin/sh: scl: linha 1: erro de sintaxe: fim de ficheiro inesperado
/bin/sh: erro ao importar definição de função para "scl"
/bin/sh: module: linha 1: erro de sintaxe: fim de ficheiro inesperado
/bin/sh: erro ao importar definição de função para "module"
/bin/sh: scl: linha 1: erro de sintaxe: fim de ficheiro inesperado
/bin/sh: erro ao importar definição de função para "scl"
/bin/sh: switchml: linha 1: erro de sintaxe: fim de ficheiro inesperado
/bin/sh: erro ao importar definição de função para "switchml"
/bin/sh: module: linha 1: erro de sintaxe: fim de ficheiro inesperado
/bin/sh: erro ao importar definição de função para "module"
/bin/sh: scl: linha 1: erro de sintaxe: fim de ficheiro inesperado
/bin/sh: erro ao importar definição de função para "scl"
/bin/sh: switchml: linha 1: erro de sintaxe: fim de ficheiro inesperado
/bin/sh: erro ao importar definição de função para "switchml"
/bin/sh: switchml: linha 1: erro de sintaxe: fim de ficheiro inesperado
/bin/sh: erro ao importar definição de função para "switchml"
/bin/sh: module: linha 1: erro de sintaxe: fim de ficheiro inesperado
/bin/sh: erro ao importar definição de função para "module"
/bin/sh: scl: linha 1: erro de sintaxe: fim de ficheiro inesperado
/bin/sh: erro ao importar definição de função para "scl"
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/***/***.git/'

```

**Comment by Arcanemagus** [comment] 2020-01-27 18:09
This looks like it might be an issue with a hook on this specific repository not finding a utility it needs. Do you see this on _all_ repositories?

**Comment by TJProgrammer** [comment] 2020-01-27 18:14
Here I used the atom git interface, but occurs in others packages like `terminus` (I didn't test all).

**Comment by Arcanemagus** [comment] 2020-01-27 18:25
Looking at the information you posted in the `terminus` issue this is a problem with your system configuration, and not an Atom issue. It looks like you have something configured to run whenever a shell is started, and that is giving you errors. You should review your shell startup scripts to see where this is coming from.

Since this doesn't appear to be an issue with Atom itself I'm going to close this issue.

**Closed by Arcanemagus** 2020-01-27 18:25 UTC
Labels: more-information-needed

**Comment by TJProgrammer** [comment] 2020-01-27 18:29
>  It looks like you have something configured to run whenever a shell is started, and that is giving you errors. You should review your shell startup scripts to see where this is coming from.

Thanks for the response, but after the atom/atom#13451, I've reinstalled my whole Fedora system, installed atom like the [instructions](https://flight-manual.atom.io/getting-started/sections/installing-atom/#red-hat-and-centos-yum-or-fedora-dnf) and I don't made any changes in shell scripts (my default shell is Gnome pure shell).

**Comment by Arcanemagus** [comment] 2020-01-27 18:50
The issue you linked is due to a bug in `scl-utils` in that specific distribution, which was worked around back in Atom 1.35.0. If you are still experiencing this it's possible Fedora has broken that _again_, but it's unlikely this is an issue with Atom.

**Comment by TJProgrammer** [comment] 2020-01-27 18:57
I'll open an issue in Fedora and see what they se me. Thanks @Arcanemagus

**Comment by TJProgrammer** [comment] 2020-02-03 19:14
Please see the comment in https://bugzilla.redhat.com/show_bug.cgi?id=1795425#c13  
@Arcanemagus, is Atom making incompatible modifications in Fedora env?

**Comment by PerBothner** [comment] 2020-02-07 21:14
I suspect this is related to issue https://github.com/atom/atom/issues/20389
I.e. an actual Atom/Electron/Node bug, not a bug in Fedora or scl-utils.
