### ISSUE TITLE
Cannot open files

### ISSUE THREAD

**Issue by sebastianv89** [atom/github#2019] opened 2019-03-19 21:17 UTC
### Description

Whenever I am working on a project that has a corresponding Github repo and I open the Github Tab (Ctrl+8), the tab just shows a purple icon with a spinner around it. After a while (sometimes seconds, sometimes about a minute) I cannot even open new files anymore. I can double-click them all I want in the tree pane to the left, but no tabs will open. Also, I cannot save any changes I make to files that are already opened (although I can modify the text on the screen).

### Steps to Reproduce

1. Open Atom
2. Open a project that has a github repo
3. Open the Github tab (ctrl+8)
4. Open/close a few files/tabs.
5. Save changes to a file

**Expected behavior:**

I can open files and save changes to opened files.

**Actual behavior:**

I cannot open new files and cannot save changes to opened files.

**Reproduces how often:**

100%, but it sometimes takes a bit longer (never more than a minute after opening the Github tab).

### Versions

```
~$ atom --version
Atom    : 1.35.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
~$ apm --version
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.35.1
python 2.7.15rc1
git 2.17.1
~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

### Additional Information

This happens for my own repositories (that I access via SSH) but also for public repositories (that I access over https). I tested it just now with https://github.com/otrv4/otrv4/.

**Comment by annthurium** [comment] 2019-03-19 21:24
thanks for reporting, @sebastianv89!  And sorry you have to deal with this bug, that's not a good experience. 

are there any errors or stack traces in the developer console?

**Comment by sebastianv89** [comment] 2019-03-19 21:34
None in either (Ctrl+Shift+I or Ctrl+Shift+J)

I don't see anything there by the way

**Comment by rsese** [comment] 2019-03-20 20:52
> Open a project that has a github repo

Can you reproduce with any GitHub repository or just a particular repository?

**Comment by sebastianv89** [comment] 2019-03-20 21:12
It seems to happen for any repository. Just now, it happened again. Here's what happened just now.
1. I closed all my projects
2. re-enabled github (ctrl+j, packages, search for github, click enable)
3. close atom
4. open atom ($ atom --safe)
5. clone repository (alt-g =); clone from https://github.com/atom/github.git
6. then the git tab opened, project loaded correctly
7. I can open files, close them, save changes etc.
8. I click the github tab.
9. I see the purple icon with spinner. After a few seconds I cannot open new files anymore

**Comment by rsese** [comment] 2019-03-21 18:04
Hmm, had you ever logged into the GitHub tab before?

Also, is this behavior new with recent versions of Atom and you didn't have this problem before?  Not sure if this is a new install for you or if you've used previous versions of Atom as well.

And just to do a quick test, I tried your repro steps in my Ubuntu 18.04 vm with 1.35.1 but couldn't reproduce.

**Comment by sebastianv89** [comment] 2019-03-21 18:51
I don't recall ever even having seen a login screen. I tried to find any old credentials, but I could find none. I did see `~/.atom/github.cson` but it only contains a single line:
```
# Store non-visible GitHub package state.
```

I only recently started using atom, I had 1.34 installed before, it didn't work there either (which is why I upgraded, to see if it would be fixed).

**Comment by rsese** [comment] 2019-03-21 23:05
If you open "Password and Keys" (or Seahorse I think it's called), do you see an entry for `atom-github`?

![ubuntu-keyring](https://github-slack.s3.amazonaws.com/monosnap/Ubuntu_64-bit_18.04_2_-_apt_repo_2019-03-21_18-01-35.png)

And I don't think there will be any extra information since you mentioned there's no devtools console errors, but if you start Atom in the foreground with `atom --foreground`, is there anything logged to terminal that looks related?

**Comment by sebastianv89** [comment] 2019-03-22 02:03
Yes! You pointed me in the right direction and I was able to fix it! Thank you for your help!

Just for posterity, here's what happened. `atom --foreground` just showed me
```
Gtk-Message: 21:46:18.705: GtkDialog mapped without a transient parent. This is discouraged.
```

I didn't have seahorse installed (I run i3 as window-manager, not gnome) but I noticed that I do have gnome-keyring. After a bit of googling I followed a suggestion to remove `~/.local/share/keyrings/login.keyring`. Opened atom again and now instead of the purple spinner I got prompted for a default password to initialize a default keystore and I saw the "login to github" button. But I also noted it created some stuff in `~/.local/share/keyrings/` (`Default.keyring` I think it was). So to see if I fixed it permanently, I removed those new files and rebooted my laptop. I noticed the file `login.keyring` was back again, but the issue was somehow fixed (?!), I could now open a github project and saw the "login to github" button. I am now logged in.

Thanks again for your help,

**Comment by annthurium** [comment] 2019-03-22 16:42
thanks for following up with a resolution! 🙌  

going to close this for now, but please feel free to re open if there are additional concerns.

**Closed by annthurium** 2019-03-22 16:42 UTC
Labels: more-information-needed

**Comment by hydroid7** [comment] 2019-11-07 08:22
I'm experiencing the same issue. No error in any of the outputs.
I created a default keyring for atom and everything was fine.

But if I do not unlock the keyring one time (may accidentally), the issue is the same as described above.

After that, my atom instance is only usable, if I disable the github module.

**Comment by Nswayze** [comment] 2020-05-14 08:23
> Yes! You pointed me in the right direction and I was able to fix it! Thank you for your help!
> 
> Just for posterity, here's what happened. `atom --foreground` just showed me
> 
> ```
> Gtk-Message: 21:46:18.705: GtkDialog mapped without a transient parent. This is discouraged.
> ```
> 
> I didn't have seahorse installed (I run i3 as window-manager, not gnome) but I noticed that I do have gnome-keyring. After a bit of googling I followed a suggestion to remove `~/.local/share/keyrings/login.keyring`. Opened atom again and now instead of the purple spinner I got prompted for a default password to initialize a default keystore and I saw the "login to github" button. But I also noted it created some stuff in `~/.local/share/keyrings/` (`Default.keyring` I think it was). So to see if I fixed it permanently, I removed those new files and rebooted my laptop. I noticed the file `login.keyring` was back again, but the issue was somehow fixed (?!), I could now open a github project and saw the "login to github" button. I am now logged in.
> 
> Thanks again for your help,

Had the exact same issue on i3 and fixed it by deleting the keyring. Thanks for your solution!

**Comment by seebs** [comment] 2021-01-13 18:53
Hey, just another random person coming along: Me too! Couldn't open files, couldn't open preferences, couldn't open about, nothing in Atom could open any window for any reason. I think I had, recently, seen a dialog box saying something like "the login keychain wasn't unlocked", and I hit cancel because if I wanted a keychain unlocked I would have unlocked it. But this apparently completely and totally wrecked Atom, it couldn't do *anything*. Removed login.keyring, and it worked normally again.

(If it matters: Also an i3 user.)

**Comment by seebs** [comment] 2021-02-11 21:31
Well, this is concerning. Nothing obvious changed, but today I can't do anything at all in atom. When I try to open any package or anything, I start getting prompted that an application wants to create a new default keyring. I can cancel, but the prompt just shows up again immediately. The prompt is modal enough to fully disable my window manager -- I can't use any other window, I can't switch desktops, nothing. Everything's fully locked. I can ssh in and kill the keyring program, at which point Atom is COMPLETELY dead -- can't open preferences, files, or anything. I have no idea what package, program, or whatever else is doing this. I can manually edit files using vi, so I can change config in order to debug this, but I wouldn't even know where to begin looking for "something in atom that's trying to access a keyring" in order to disable it.

It really seems like this functionality should be less intrusive, I think -- failure to authorize a keyring should not be completely breaking the entire user interface!

(Note: I specifically, absolutely, DO NOT under any circumstances want to sign in. I am making a considered choice not to create a keyring and authenticate everything. That should work.)
