### ISSUE TITLE
Discarding Changes deletes content of File

### ISSUE THREAD

**Issue by WashirePie** [atom/github#1375] opened 2018-04-03 08:19 UTC
### Prerequisites

* Remote TFS repository (It's huge: 23'000 Files, 2400 Folders, approx. 1GB)
* Running TortoiseGIT Shell Extension - parallel
* Custom grammars are being used
* Packetized Atom - packages, config.cson and keymap.cson were installed by copy / pasting*
* Windows 7 64 Bit

### Description

When I save changes in a file and try to 'Discard Changes' - by right clicking and choosing the option or by using 'Ctrl + Backspace' - the changes won't be discarded. When you go ahead and click on the file do get a diff, it will just say "File has no Contents" the Symbol in the 'Unstaged Changes' pane still shows as if the file had only been 'Changed'.

When you restart Atom tough, it will Display the Symbol as 'Deleted'. Clicking on it for the diff, reveals that all Content has been deleted from the file.

### Steps to Reproduce

1. Make changes in a file
2. Save the file by either using 'Ctrl+S' or 'File > Save'
3. If not open, open the git pane by using 'Ctrl+Shift+9'
4. Click on the changed file to display it's diff
5. Discard it's changes by using 'Ctrl+Backspace' or rightclick > 'Discard Changes'
6. Check wheter it says 'File has no content' in the diff Tab & wheter the Symbol in the unstaged changes view represents 'File Changed'
7. Close / Open Atom 

**Expected behavior:**

I expected that it would discard the changes i've made to the file and transform it to it's original state.

Addtionally, if you do step 1. - 6. and then try to Close the tab with your changed file open, it says that 'Changes have been made' and 'if you'd want to save?'. Hitting 'Save' leaves you with a Dialog which says: 'File could not be saved' and 'Error: permission denied':
![atom_resave](https://user-images.githubusercontent.com/38029550/38238398-3c312416-3719-11e8-970c-5145b4149521.png)

**Actual behavior:**

It deleted the Content of the file and would only show it when Atom was restarted.

**Reproduces how often:**

Always, I've never had it differently

### Versions

apm 1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.0
python
git 2.16.2.windows.1
visual studio

* github Package v0.10.3 

### Additional Information

 \*  Since I work for a Company and i'm trying to implement Atom in our toolchain, it would need to be easy to distribute Atom onto other workers machines. For that purpose I've set Atom up and copied all packages from **%USERNAME%/.atom/packages** aswell as the **config.cson** and **keymap.cson** in my companies remote repository. So other workers could download and install Atom and copy / paste the additional files in their **%USERNAME%/.Atom** Folder.
I know that this is far from ideal, but that's how it is atm.

**Comment by WashirePie** [comment] 2018-04-05 13:29
Here's an Update:

I've found out that if I restart Atom between step 4 & 5 (After making changes to a file and saving it),
I am able to discard the changes just fine!

**Comment by Ben3eeE** [comment] 2018-04-05 14:15
Thanks for the report @WashirePie :bowing_man: 

Is your repository located in the user directory? This sounds similar to https://github.com/atom/atom/issues/17013 and it's mentioned there that moving the project folder from the user directory helped resolve the issue.

**Comment by WashirePie** [comment] 2018-04-06 05:56
I've had a look at the mentioned issue. And it seems very similar looking at the post by 
 Our repository / workfolder is located in our standardized location C:\Projects\repository

**Comment by WashirePie** [comment] 2018-04-06 06:58
Sadly, it seems to have no effect on curing the issue.
I'll clone our repo to another harddrive and see if it still occurs.

**Comment by WashirePie** [comment] 2018-04-06 12:40
## SOLUTION
I've finally found the issue (sort of).
As written in the original post, I've distributed my original config.cson file. I've narrowed it down to the user-id, which should be unique. But Atom doesn't refresh this id when it should be (That is when the config is used on a different machine / setup), which makes the config.cson **unsharable** (Which was already known. Doh!) Thanks for the help tough @Ben3eeE 

Maybe this could help @Weranders or @markageorge

**Comment by WashirePie** [comment] 2018-04-12 08:26
@rsese I just tried 1.24.1 and it works flawlessly! I'm gonna try it in the beta 1.26.0 aswell.

**Comment by WashirePie** [comment] 2018-04-12 08:59
@rsese It also doesn't work in the 1.26.0 beta. Too bad

**Comment by rsese** [comment] 2018-04-13 00:15
Thanks for confirming @WashirePie - it was mentioned in https://github.com/atom/atom/issues/17013 that 1.24.1 worked for someone but 1.25 and above didn't so I was curious if you would see the same behavior.

**Comment by Ben3eeE** [comment] 2018-04-17 21:07
@WashirePie Thank you for all the information here. We are going to close this as a duplicate of https://github.com/atom/atom/issues/17013. If you could check if you can reproduce this issue with the `github` package disabled and report back in that issue that would be great, Thanks 🙇 

---

We noticed that this is a duplicate of https://github.com/atom/atom/issues/17013. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2018-04-17 21:07 UTC
Labels: more-information-needed
