### ISSUE TITLE
Only loaded in dev mode when starting atom from cmd line

### ISSUE THREAD

**Issue by tylerFowler** [atom/github#1361] opened 2018-03-22 21:11 UTC
For a while now I've been seeing some funky behavior where the github integration is only active in dev mode (e.g. `atom -d`) or when I've started atom by opening the Application via Finder. When running Atom this way it functions as normal but when running atom from the command line (e.g. `atom`) I can't use the integration at all.

It shows up as 'enabled' in Settings -> Packages and is not under the 'development packages' section, and the 'Git' panel is created but it's completely empty none of the integration commands show in command palette.

Any ideas as to what might be causing this? Can confirm this also happens in safe mode, but would be happy to post the community packages I have installed if it helps (spoiler alert: I do have git-plus).

## Versions:
```
OS: macOS High Sierra v10.13.3
```

```
Atom    : 1.26.0-beta0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

```
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.0-beta0
python 2.7.10
git 2.16.2
```

**Comment by maxwinslow-banjo** [comment] 2018-05-02 22:28
Just wanted to piggyback on this issue. Same thing is happening for me. Git and Github Tab is not working when opening atom via command line `atom .` unless it is in dev mode `atom -d  .` or if I am opening it by clicking the icon in Finder.

This is the error I am getting in the console.
<img width="803" alt="screen shot 2018-05-02 at 4 24 10 pm" src="https://user-images.githubusercontent.com/36172307/39552306-e29fd9f0-4e25-11e8-8110-ffdb14b64908.png">


```
Atom :  1.26.1
Electron: 1.7.11
Chrome: 58.0.3029.110
Node: 7.9.0 
```

**Comment by smashwilson** [comment] 2018-05-03 00:34
@tylerFowler do you have a similar stacktrace in your dev console?

@maxwinslow-banjo from the stack, this looks like an old issue (#833) that we've never been able to find a good answer for. Do you happen to have the environment variable `NODE_ENV` set to `development`? That can mess up React I'm afraid.

**Comment by smashwilson** [comment] 2018-05-03 11:53
Yeah, React seems to get confused when you run it with a different `NODE_ENV` than we had set while we were packaging it.

Thanks for confirming. I'll close this as a duplicate of #833, then; subscribe over there for updates 🙇

**Closed by smashwilson** 2018-05-03 11:53 UTC
