### ISSUE TITLE
Uncaught Error: $ATOM_HOME/compile-cache\less\40e22529c8729b65e1d700a7ae3f73d57ed1288f\content\74...

### ISSUE THREAD

**Issue by vishnyaspez** [atom/github#983] opened 2017-06-24 11:31 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 ia32
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [github](https://github.com/atom/github) package 0.3.3

### Stack Trace

Uncaught Error: C:\Users\LG\.atom\compile-cache\less\40e22529c8729b65e1d700a7ae3f73d57ed1288f\content\74a3946e628ab9f9c082ce4958f7c4816be256e1\git-panel.json does not belong to repo null

```
At C:\Users\LG\AppData\Local\atom\app-1.18.0\resources\app\node_modules\github\lib\controllers\root-controller.js:807

Error: C:\Users\LG\.atom\compile-cache\less\40e22529c8729b65e1d700a7ae3f73d57ed1288f\content\74a3946e628ab9f9c082ce4958f7c4816be256e1\git-panel.json does not belong to repo null
    at RootController.viewChangesForCurrentFile (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/github/lib/controllers/root-controller.js:807:19)
    at RootController.viewUnstagedChangesForCurrentFile (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/github/lib/controllers/root-controller.js:812:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.18.0/resources/app/src/atom-environment.js:1320:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.18.0/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -4:03.4.0 core:backspace (input.hidden-input)
  2x -4:00.5.0 core:paste (div.line)
     -2:26.4.0 core:backspace (input.hidden-input)
     -2:23.4.0 core:paste (div.line)
     -2:09.8.0 grammar-selector:show (atom-text-editor.editor)
     -2:06.0 encoding-selector:show (atom-text-editor.editor)
     -2:02.9.0 line-ending-selector:show (atom-text-editor.editor)
     -1:59.4.0 core:paste (div.line)
     -1:57.9.0 core:confirm (input.hidden-input)
     -1:54.4.0 go-to-line:toggle (atom-text-editor.editor)
     -1:48 core:cut (div.line)
     -1:45 core:delete (div.line)
     -1:41.7.0 github:view-unstaged-changes-for-current-file (div.line)
```

### Non-Core Packages

```
linter-write-good 0.9.0 
```

**Comment by BinaryMuse** [comment] 2017-06-25 17:52
This appears to be a duplicate of https://github.com/atom/github/issues/950

**Closed by BinaryMuse** 2017-06-25 17:52 UTC
