### ISSUE TITLE
Uncaught Error: ~/Escritorio/starbrandBasic/package.json does not belong to repo null

### ISSUE THREAD

**Issue by arenasgtz92** [atom/github#1005] opened 2017-07-03 22:29 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [github](https://github.com/atom/github) package 0.3.3

### Stack Trace

Uncaught Error: /home/arenas/Escritorio/starbrandBasic/package.json does not belong to repo null

```
At /home/andrei/atom-1.11.1/out/app/node_modules/tree-view/lib/file.coffee:92378

Error: /home/arenas/Escritorio/starbrandBasic/package.json does not belong to repo null
    at RootController.viewChangesForCurrentFile (/opt/atom/resources/app/node_modules/github/lib/controllers/root-controller.js:807:19)
    at RootController.viewStagedChangesForCurrentFile (/opt/atom/resources/app/node_modules/github/lib/controllers/root-controller.js:816:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/opt/atom/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/opt/atom/resources/app/src/atom-environment.js:1320:34)
    at EventEmitter.outerCallback (/opt/atom/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:17.6.0 tree-view:show-current-file-in-file-manager (div.lines)
     -0:06.3.0 github:view-staged-changes-for-current-file (div.)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2017-07-04 03:46
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/github/issues/950. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-07-04 03:46 UTC
