### ISSUE TITLE
Uncaught Error: ~/Documents/ISS247/ISS Framework/swagger/css/style.css does not belong to repo null

### ISSUE THREAD

**Issue by sanket876** [atom/github#982] opened 2017-06-24 09:26 UTC
[Enter steps to reproduce:]

1. Open any html or js file
2. Right click and View Unstaged Chages. It will thorw error

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [github](https://github.com/atom/github) package 0.3.3

### Stack Trace

Uncaught Error: /home/sanket/Documents/ISS247/ISS Framework/swagger/css/style.css does not belong to repo null

```
At /usr/share/atom/resources/app/node_modules/github/lib/controllers/root-controller.js:807

Error: /home/sanket/Documents/ISS247/ISS Framework/swagger/css/style.css does not belong to repo null
    at RootController.viewChangesForCurrentFile (/usr/share/atom/resources/app/node_modules/github/lib/controllers/root-controller.js:807:19)
    at RootController.viewUnstagedChangesForCurrentFile (/usr/share/atom/resources/app/node_modules/github/lib/controllers/root-controller.js:812:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/usr/share/atom/resources/app/src/atom-environment.js:1320:34)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -4:14.5.0 application:add-project-folder (div.tool-panel.tree-view)
  2x -3:18.8.0 core:close (input.hidden-input)
     -3:15 fuzzy-finder:toggle-file-finder (div.panels-item)
  4x -3:07.0 core:move-down (input.hidden-input)
     -3:05.9.0 core:move-up (input.hidden-input)
     -3:05.4.0 core:confirm (input.hidden-input)
     -2:59.3.0 command-palette:toggle (input.hidden-input)
  2x -2:56.9.0 core:move-down (input.hidden-input)
     -2:56.2.0 core:confirm (input.hidden-input)
     -2:56.2.0 pane:split-left (input.hidden-input)
     -1:45.5.0 core:undo (input.hidden-input)
     -1:23.4.0 core:backspace (input.hidden-input)
     -1:22.2.0 core:move-down (input.hidden-input)
  2x -1:18.5.0 core:undo (input.hidden-input)
  2x -1:06.0 core:move-right (input.hidden-input)
     -0:19.2.0 github:view-unstaged-changes-for-current-file (div.line)
```

### Non-Core Packages

```
pigments 0.39.1 
```

**Comment by BinaryMuse** [comment] 2017-06-25 17:51
This appears to be a duplicate of https://github.com/atom/github/issues/950.

**Closed by BinaryMuse** 2017-06-25 17:51 UTC
