### ISSUE TITLE
Hunks for staging are not visible in 'Unstaged Changes' tab

### ISSUE THREAD

**Issue by DavidCarpus** [atom/github#1074] opened 2017-08-02 16:43 UTC
### Description
When I select a file in the git panel it displays the existence of multiple hunks (only a line or two for each hunk) but does not display the hunk lines themselves.

The only 'non core' package I have not disabled at this point is emmet.

**Expected behavior:**
The screenshots I have seen showing the git integration seem to indicate I should see the actual modified lines. 

**Actual behavior:**
The hunk 'data' is displayed but not the actual lines of code

**Reproduces how often:**
100%

### Versions
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

Ubuntu 16.04.3 LTS
Linux E6420 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Additional Information

![gitdiffnotvisible](https://user-images.githubusercontent.com/24421399/28884507-269bc27c-7780-11e7-8f09-bb68d4a84f7b.png)

**Comment by BinaryMuse** [comment] 2017-08-02 17:17
Hey @DavidCarpus — does this reproduce for you in [Safe Mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?

**Comment by DavidCarpus** [comment] 2017-08-02 18:31
Yes.

**Comment by BinaryMuse** [comment] 2017-08-02 18:48
This is really interesting — I can see bits of green in the screenshot (added lines are colored in green) and some odd looking pixels to the left of the green that looks like it might be trying to display text? Wonder if it could be a font rendering thing.

@DavidCarpus If you open the developer tools and use the element selector, do you actually see the `HunkView-line` elements in the DOM? If so, does changing the font or font size help at all? I assume regular text editors appear normally?

![github-package-diff-inspect](https://user-images.githubusercontent.com/189606/28889274-633095c6-7778-11e7-9058-988a987d431a.gif)

**Comment by BinaryMuse** [comment] 2017-08-02 18:48
Also: do you have any custom styles in your user stylesheet that might be affecting layout?

**Comment by DavidCarpus** [comment] 2017-08-02 19:42
I found a hunkview for some added text and it does indeed have a span in the DOM with the text.
Interestingly the font-size for .github-HunkView-line is 1px.
When I disable that particular style element the code shows up.

![gitdifffont-size](https://user-images.githubusercontent.com/24421399/28891613-1cd9eebc-7799-11e7-9c37-92141cf7a5d9.png)

**Comment by BinaryMuse** [comment] 2017-08-07 16:58
Okay, thanks for digging into that. Looks like something weird is going on here with how we watch the editor font size setting.

**Comment by DavidCarpus** [comment] 2017-08-11 20:19
![image](https://user-images.githubusercontent.com/24421399/29230309-6da51f7e-7eb0-11e7-93a0-ca97e45e4258.png)

Not sure if needs to be logged separately or not but I tried to 'force' the font size by adding to my style.less but apparently the github-package-styles seems to be loaded later than the 'user' stylesheet?

**Comment by DavidCarpus** [comment] 2017-12-18 12:09
It appears at some point something was changed between 1.18.0 and 1.22.1 that appears to have fixed this. 
**.github-HunkView-line {font-size}** now seems to be pulling the font size from the editor settings in _preferences_.
It might still be nice if the _user_ stylesheet could override this setting but not nice enough at this point if it requires any significant re-architecture work.

**Comment by simurai** [comment] 2018-01-18 03:00
> but apparently the github-package-styles seems to be loaded later than the 'user' stylesheet?

This seems like a bug and `styles.less` should be loaded last. In the meantime you might can try to add a higher specificity. Like repeating the class name:

```less
.github-HunkView-line.github-HunkView-line {
  font-size: 0.9em;
}
```
or use `!important`:

```less
.github-HunkView-line {
  font-size: 0.9em !important;
}
```

that should override the styles from the github package even if loaded before.

**Comment by kuychaco** [comment] 2018-01-19 01:19
I'm going to go ahead and close this since the original issue has been resolved. I've opened a separate issue to capture the stylesheet priority issue (https://github.com/atom/github/issues/1292)

Thanks for the report and help digging into this @DavidCarpus!

**Closed by kuychaco** 2018-01-19 01:19 UTC
Labels: bug
