### ISSUE TITLE
Github stuck on loading

### ISSUE THREAD

**Issue by Anchovy-s3** [atom/github#2616] opened 2021-01-26 09:38 UTC
### Description
Github stuck on loading when open GitHub on my Atom editor.

### Steps to Reproduce

1. Make new directory.
2. Click on GitHub in Atom.
3. Click on "Publish on Github".

**Expected behavior:**
Displaying user name.

**Actual behavior:**
User name field is endless loading.
<img width="599" alt="スクリーンショット 2021-01-26 18 13 29" src="https://user-images.githubusercontent.com/59955057/105825804-56a8bf00-6003-11eb-8239-377a561b0d57.png">

**Reproduces how often:**
Every times.

### Versions
<img width="698" alt="スクリーンショット 2021-01-26 18 24 38" src="https://user-images.githubusercontent.com/59955057/105826143-c3bc5480-6003-11eb-813f-e30d98a2b004.png">
<img width="599" alt="スクリーンショット 2021-01-26 18 25 13" src="https://user-images.githubusercontent.com/59955057/105826210-d6cf2480-6003-11eb-986f-0c21daafb99d.png">
Atom    : 1.54.0
<br>
Electron: 6.1.12
<br>
Chrome  : 76.0.3809.146
<br>
Node    : 12.4.0
<br>
<br>

**Comment by JackHumphries9** [comment] 2021-01-26 09:41
Hi,
   Do you have any proxy servers or anything like that which might block GitHub's servers? This could be causing the infinite load.

**Comment by Anchovy-s3** [comment] 2021-01-26 11:28
Thanks for reply.
I checked network settings but all proxy settings is turn off.
<img width="780" alt="スクリーンショット 2021-01-26 20 24 05" src="https://user-images.githubusercontent.com/59955057/105839485-e9058e80-6014-11eb-863d-d9aebf4c0b48.png">

**Comment by LoganTann** [comment] 2021-01-27 14:11
Same issue with atom 1.54.0 x64 Windows 7, Github plugin 3.36.2

good to know, initializing the repository with the git tab seems to recognize me.
![image](https://user-images.githubusercontent.com/28659185/106002691-b78ed080-60b1-11eb-8ffb-675d4a65d331.png)

but not the github tab:
![image](https://user-images.githubusercontent.com/28659185/106002870-e9079c00-60b1-11eb-9823-cc280355dac8.png)

**Comment by hirin-byte** [comment] 2021-02-03 04:14
hi, i begginer in this the atom and github. But i fix this error with this steps:

1.I download this package in atom: platformio-atom-ide-terminal.
![image](https://user-images.githubusercontent.com/76855526/106696252-b0385d00-65b2-11eb-8861-025ea2f8d425.png)

2.Restart Atom and open functions selector with Shift + Ctrl +P and tipe Ide Terminal New or press Alt+Shift+T :
![image](https://user-images.githubusercontent.com/76855526/106696532-4bc9cd80-65b3-11eb-95b5-5c3cddb54abc.png)

3.With the new ide terminal open in the project or script, i type *git remote add origin (and here add the link repo)* and now you have available the github tab for publish your content there.
![image](https://user-images.githubusercontent.com/76855526/106697098-7d8f6400-65b4-11eb-9591-89ce6c0edc5a.png)


(Sorry for my bad English and i hope it works for you)

**Comment by LoganTann** [comment] 2021-02-03 07:16
> 3.With the new ide terminal open in the project or script, i type _git remote add origin (and here add the link repo)_ and now you have available the github tab for publish your content there.

Oh I see ! In that case, just using the system's terminal in the project folder would work too.

But this issue have to be fixed

**Comment by smashwilson** [comment] 2021-02-05 20:42
This is a duplicate of https://github.com/atom/github/issues/2542. Please subscribe there for updates!

It's also partially fixed in the package build currently in [Atom's nightly channel](https://atom.io/nightly). While you can _technically_ still have the same problem if you run a command like `GitHub: Publish Repository`  or `GitHub: Create Repository` directly from the command palette, the GitHub tab itself will at least prompt you to authenticate before showing you the buttons, now.

**Closed by smashwilson** 2021-02-05 20:42 UTC
