### ISSUE TITLE
How to set the account? 

### ISSUE THREAD

**Issue by pacez** [atom/github#1033] opened 2017-07-14 01:35 UTC
Everytime, I need input the third repository account & password when I use the github plugin ?  
I can't found the account setting on the github setting.

**Comment by LuisRodriguezLD** [comment] 2017-07-18 16:58
Same here. It asks my credentials every single time I try to push, pull or fetch

**Comment by rsese** [comment] 2017-07-21 01:07
Thanks for the report!  I think this is basically a duplicate of https://github.com/atom/github/issues/861 so you can subscribe there for updates.  For now, if you use a credential helper you shouldn't be prompted for a username/password:

https://help.github.com/articles/caching-your-github-password-in-git/

If you do have a credential helper setup and it's working for operations on the command line, then I think you might be hitting the problem being discussed in https://github.com/atom/github/issues/436#issuecomment-307244773.

As a side note, we require the template to be filled out on all new issues and pull requests so please fill it out completely in the future for new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

This looks like a duplicate of https://github.com/atom/github/issues/861

**Closed by rsese** 2017-07-21 01:07 UTC

**Comment by jonnylink** [comment] 2017-08-22 13:44
Word to the wise, if you follow the other tickets you'll just end up back here.
