### ISSUE TITLE
An unknown error occurred

### ISSUE THREAD

**Issue by corysimmons** [atom/github#1100] opened 2017-08-15 06:20 UTC
- Added token
- Hit button

![image](https://user-images.githubusercontent.com/224636/29304293-3a9e8892-8160-11e7-98a1-136b33707991.png)

**Comment by rsese** [comment] 2017-08-17 21:36
Going to go ahead and close as a dupe of https://github.com/atom/github/issues/922.

@corysimmons - is the repository you're working on a private organization repository?

Also as a side note, it's super helpful if you can fill out the issue template since that gives us a lot of baseline information.  E.g.:

* What version of Atom are you using (`atom -v`)?
* What operating system are you on?

**Closed by rsese** 2017-08-17 21:36 UTC

**Comment by corysimmons** [comment] 2017-08-18 03:43
>is the repository you're working on a private organization repository

It very well might have been.

```
Atom    : 1.19.2
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**Comment by rsese** [comment] 2017-08-18 20:30
Thanks for confirming - I think what I described in this issue where people reported the same issue might help https://github.com/atom/github/issues/1025#issuecomment-323140307.

Let me know if you still have trouble and you think it might not be related to OAuth App restrictions,
