### ISSUE TITLE
Amend button removed

### ISSUE THREAD

**Issue by mrdonee** [atom/github#1475] opened 2018-05-18 18:37 UTC
### Description

The other day I was using Atom with my much-loved 'git-amend' check box next to the commit button and then suddenly it was gone

### Steps to Reproduce

Not sure how or why this happened, I assume that maybe the package auto-updated and the button may have been moved or removed

**Expected behavior:**

I expected this button to remain there where I am used to it

**Actual behavior:**

It is gone!!!

**Reproduces how often:**

100%

### Versions

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.27.0
python 2.7.10
git 2.15.1
MacOS High Sierra Version 10.13.4

### Additional Information

<img width="382" alt="amendbutton" src="https://user-images.githubusercontent.com/16673004/40252019-db71735c-5a8f-11e8-9b30-eb3401e4b59e.png">

<img width="401" alt="noamendbutton" src="https://user-images.githubusercontent.com/16673004/40252026-dfcc387e-5a8f-11e8-9f1a-a712bc01f7aa.png">

**Comment by Arcanemagus** [comment] 2018-05-18 18:45
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/github/issues/1466. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2018-05-18 18:45 UTC
