### ISSUE TITLE
Clicking on a staged or unstaged change will open the tree view even though it's closed by the user

### ISSUE THREAD

**Issue by varemenos** [atom/github#1380] opened 2018-04-06 12:46 UTC
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]?
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?
* Have you checked the FAQs on the [message board][message-board] for common solutions?
* Have you checked that your issue [isn't already filed][already-filed]?

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

Clicking on any unstaged or staged changes to display the diff view (to review the changes) also displays the the tree view even though the user had the tree view closed.

### Steps to Reproduce

1. Open a git project with Atom
2. Close the tree view dock
3. From the Git Dock click on a file with staged or unstaged changes

**Expected behavior:**

I expected Atom to respect my choice of having the tree view closed.
If the purpose of opening the tree view was so the user had a clearer idea of what file was being reviewed prior to committing, then I'd say the argument is kind of invalid since we already have a clear view of the file being reviewed by it's project's filepath being mentioned in the Git Dock (the item I just clicked).

**Actual behavior:**

Every time I clicked any of the changed files in the Git Dock, the tree view would be displayed.

**Reproduces how often:**

100% of the times I have my tree view closed and clicking on a staged or unstaged file for a review of it's diff.

### Versions

```
» atom --version

Atom    : 1.25.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

```
» apm --version

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.1
python 3.6.4
git 2.16.1
```

macOS 10.13.3

**Comment by Arcanemagus** [comment] 2018-04-06 20:30
I'm unable to reproduce this on Atom v1.26.0-beta1. Do you see this in [Safe Mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?

**Comment by Ben3eeE** [comment] 2018-04-13 07:34
Thanks for taking the time to contribute!

This happens because the `tree-view` package settings are configured with both `Auto Reveal` and `Focus on Reveal` /cc: https://github.com/atom/tree-view/issues/796

We noticed that this is a duplicate of https://github.com/atom/tree-view/issues/796. You may want to subscribe to https://github.com/atom/atom/pull/17088 for updates on when a fix be available in an Atom release. In the meantime you can disable either of the `Auto Reveal` or `Focus on Reveal settings`

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2018-04-13 07:34 UTC
Labels: duplicate
