### ISSUE TITLE
Uncaught Error: ~/AppData\Local\Temp\192.168.68.130\wwwroot\opaparser_numericGames\grabber2.js do...

### ISSUE THREAD

**Issue by nekkolliakos** [atom/github#1008] opened 2017-07-04 19:44 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [github](https://github.com/atom/github) package 0.3.3

### Stack Trace

Uncaught Error: C:\Users\nek\AppData\Local\Temp\192.168.68.130\wwwroot\opaparser_numericGames\grabber2.js does not belong to repo null

```
At C:\Users\nek\AppData\Local\atom\app-1.18.0\resources\app\node_modules\github\lib\controllers\root-controller.js:807

Error: C:\Users\nek\AppData\Local\Temp\192.168.68.130\wwwroot\opaparser_numericGames\grabber2.js does not belong to repo null
    at RootController.viewChangesForCurrentFile (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/github/lib/controllers/root-controller.js:807:19)
    at RootController.viewStagedChangesForCurrentFile (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/github/lib/controllers/root-controller.js:816:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.18.0/resources/app/src/atom-environment.js:1320:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.18.0/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:19.4.0 github:view-staged-changes-for-current-file (div.icon-right)
```

### Non-Core Packages

```
autocomplete-clang 0.11.3 
build 0.68.0 
busy 0.7.0 
file-icons 2.1.7 
ftp-remote-edit 0.11.6 
intentions 1.1.2 
language-ini 1.19.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.6.1 
minimap 4.28.2 
platformio-ide 2.0.0-beta.6 
platformio-ide-debugger 1.2.2 
platformio-ide-terminal 2.5.1 
tool-bar 1.1.0 
```

**Comment by rsese** [comment] 2017-07-06 01:59
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/github/issues/950. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-07-06 01:59 UTC
