### ISSUE TITLE
Uncaught Error: ~/Desktop\portfolio\toplist\index.html does not belong to repo null

### ISSUE THREAD

**Issue by swapu258** [atom/github#1022] opened 2017-07-09 20:14 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [github](https://github.com/atom/github) package 0.3.3

### Stack Trace

Uncaught Error: C:\Users\user\Desktop\portfolio\toplist\index.html does not belong to repo null

```
At C:\Users\user\AppData\Local\atom\app-1.18.0\resources\app\node_modules\github\lib\controllers\root-controller.js:807

Error: C:\Users\user\Desktop\portfolio\toplist\index.html does not belong to repo null
    at RootController.viewChangesForCurrentFile (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/github/lib/controllers/root-controller.js:807:19)
    at RootController.viewStagedChangesForCurrentFile (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/github/lib/controllers/root-controller.js:816:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.18.0/resources/app/src/atom-environment.js:1320:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.18.0/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  9x -1:45.1.0 core:backspace (input.hidden-input)
  6x -1:39.3.0 core:move-right (input.hidden-input)
     -1:37.5.0 editor:newline (input.hidden-input)
     -1:35.9.0 autocomplete-plus:confirm (input.hidden-input)
     -1:35.9.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:32.2.0 core:backspace (input.hidden-input)
  2x -1:27.8.0 core:move-down (input.hidden-input)
  6x -1:27 core:move-left (input.hidden-input)
  7x -1:24.7.0 core:backspace (input.hidden-input)
     -1:18.7.0 intentions:highlight (input.hidden-input)
     -1:18.4.0 core:save (input.hidden-input)
     -0:52.3.0 atom-beautify:beautify-editor (div.line)
     -0:45.3.0 intentions:highlight (input.hidden-input)
     -0:45 core:save (input.hidden-input)
     -0:36.5.0 tree-view:reveal-active-file (div.)
     -0:26.6.0 github:view-staged-changes-for-current-file (div.)
```

### Non-Core Packages

```
atom-beautify 0.30.3 
atom-typescript 11.0.6 
busy-signal 1.4.3 
intentions 1.1.2 
linter 2.2.0 
linter-ui-default 1.6.2 
```

**Comment by rsese** [comment] 2017-07-11 08:43
Thanks for taking the time to contribute!

We noticed that this looks like a duplicate of https://github.com/atom/github/issues/950. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-07-11 08:43 UTC
