### ISSUE TITLE
Github package not working on atom 1.19 on macOS Sierra 10.12.6

### ISSUE THREAD

**Issue by vinicius0026** [atom/github#1095] opened 2017-08-10 17:21 UTC
### Description

Github package doesn't work.

When I had just updated atom from 1.18 to 1.19, this package seemed to work, but it suddenly crashed and, since then, I'm unable to make it run again.

### Steps to Reproduce

I can't reproduce the crash, but now just opening atom (even in safe mode or after reseting to factory defaults) causes the error.

**Expected behavior:**

Github package should work.

**Actual behavior:**

The console reports the following error on startup

![captura de tela 2017-08-10 as 14 11 58](https://user-images.githubusercontent.com/3792147/29182598-e7af735e-7dd5-11e7-85ca-745473b6ab37.png)

**Reproduces how often:**

Always

### Versions

OS: macOS Sierra 10.12.6
Atom: 1.19.0
Electron: 1.6.9
Chrome: 56.0.2924.87
Node: 7.4.0
github package: 0.3.4-0

### Additional Information

If I right click a file and click `View Unstaged Changes` or `View Staged Changes` the same error as above is logged to the console.

I see that the package is at version 0.4.2, and I tried to update it, but I was unable to do so. Tried both by atom GUI and by `apm upgrade`.

**Comment by 50Wliu** [comment] 2017-08-14 02:05
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #979. You may want to subscribe there for updates.  In addition, check to see if your `NODE_ENV` variable is set to `development`, and if so, try changing it to `production` or removing it instead.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-08-14 02:05 UTC
