### ISSUE TITLE
Improve Conflict Navigation when resolving conflicts

### ISSUE THREAD

**Issue by Haacked** [atom/github#852] opened 2017-05-19 16:58 UTC
After a pull, I had a file with merge conflicts. When I clicked on the file in the Git pane, nothing seemed to change in my code view.

Oh! It's because the first conflict was on line 400 which was not in view.

Also, after I resolve each conflict, it'd be nice to have an easy way to jump to next conflict. If there is one, it's not readily apparent.

### Suggestions

1. When you click on a conflicted file, scroll the first conflict into the view.
2. Add keyboard and UI navigation to the next conflict.

**Comment by smashwilson** [comment] 2017-05-19 17:06
Duplicate of #812 (and #813 should help this for many users, too).

**Closed** 2017-05-19 17:06 UTC
Labels: duplicate, enhancement
