### ISSUE TITLE
Uncaught Error: ~/ruby_garage/homeworks/Codebreaker/codebreaker/lib/codebreaker.rb does not belon...

### ISSUE THREAD

**Issue by Dimetriu** [atom/github#1030] opened 2017-07-13 07:30 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [github](https://github.com/atom/github) package 0.3.3

### Stack Trace

Uncaught Error: /home/dima/ruby_garage/homeworks/Codebreaker/codebreaker/lib/codebreaker.rb does not belong to repo null

```
At /usr/share/atom/resources/app/node_modules/github/lib/controllers/root-controller.js:807

Error: /home/dima/ruby_garage/homeworks/Codebreaker/codebreaker/lib/codebreaker.rb does not belong to repo null
    at RootController.viewChangesForCurrentFile (/usr/share/atom/resources/app/node_modules/github/lib/controllers/root-controller.js:807:19)
    at RootController.viewUnstagedChangesForCurrentFile (/usr/share/atom/resources/app/node_modules/github/lib/controllers/root-controller.js:812:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/usr/share/atom/resources/app/src/atom-environment.js:1320:34)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -9:16.6.0 core:copy (input.hidden-input)
     -9:14.3.0 editor:newline (input.hidden-input)
     -9:13.3.0 core:paste (input.hidden-input)
     -9:11.9.0 core:move-left (input.hidden-input)
     -9:11.5.0 editor:select-to-beginning-of-word (input.hidden-input)
  3x -9:08.5.0 core:save (input.hidden-input)
     -2:29.5.0 core:paste (input.hidden-input)
  2x -2:23 core:delete (input.hidden-input)
     -2:09.0 core:save (input.hidden-input)
     -1:47.9.0 core:paste (input.hidden-input)
     -1:45.4.0 core:save (input.hidden-input)
     -1:39.2.0 core:backspace (input.hidden-input)
  3x -1:37.6.0 core:save (input.hidden-input)
     -0:33.7.0 github:toggle-git-tab (ul.list-inline.tab-bar.inset-panel)
     -0:13.4.0 github:view-unstaged-changes-for-current-file (span.syntax--keyword.syntax--control.syntax--module.syntax--ruby)
```

### Non-Core Packages

```
platformio-ide-terminal 2.5.3 
```

**Comment by rsese** [comment] 2017-07-18 08:19
Thanks for taking the time to contribute!

We noticed that this looks like a duplicate of https://github.com/atom/github/issues/950. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-07-18 08:19 UTC
