### ISSUE TITLE
Atom Git Hub login button do not work

### ISSUE THREAD

**Issue by swessey** [atom/github#1343] opened 2018-03-10 22:44 UTC
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]? Yes
* Have you followed all applicable steps in the [debugging guide][debugging-guide]? Yes 
* Have you checked the FAQs on the [message board][message-board] for common solutions? Yes
* Have you checked that your issue [isn't already filed][already-filed]? Yes

### Description

When I Try to login using the button with the github tab it do not do anything at all.

### Steps to Reproduce

1. Go to packages--> GitHub --> Toggle GitHub Tab
2. Press login
3. Go sign in on "https://github.atom.io/" for the key
4. Insert the key in the input form
5. Press login and nothing will happen 

**Expected behavior:**

Login and see the Changes menu. 

**Actual behavior:**

Nothing Only got a long error in the developer console

**Reproduces how often:**

everytime I try to login

### Versions
macOSx Sierra: 10.12.6
Atom : 1.24.1
apm: 1.18.12

### Additional Information

Please include any additional information, configuration or data that might be necessary to reproduce the issue. Screenshots, if appropriate, are helpful as well.

If your issue involves a repository, and that repository is public, please include a link to it.

**Comment by lnxg33k** [comment] 2018-03-10 23:19
Yeah, I am facing the same issue.
macOS High Sierra 10.13.3 
Atom: 1.24.1
apm: 1.18.12

**Comment by HaoyangFan** [comment] 2018-03-11 07:17
same here

**Comment by smashwilson** [comment] 2018-03-11 15:40
Duplicate of #1340, and fixed in #1344. 😄

**Closed** 2018-03-11 15:41 UTC
