### ISSUE TITLE
Unable to commit if the Commit Message starts with # (sharp)

### ISSUE THREAD

**Issue by RrOoSsSsOo** [atom/github#1299] opened 2018-02-01 11:52 UTC
### Description

If a commit message starts with character # (sharp) Atom will not enable to do the commit
```
Unable to commit
Aborting commit due to empty commit message.
```
if a commit message starts with any other start character, i.e. a space and then # (sharp), Atom will do the commit without any problem

### Steps to Reproduce

1. Create or Edit a file in a git repository
2. Write the _Commit message_ "#my abc"
3. Click _Commit_
4. Obtain the error
5. Write the _Commit message_ " #my abc" (with an initial space)
6. Click _Commit_
7. Commit work

**Expected behavior:**

Writing any commit message (like for the app Github Desktop - [desktop.github.com](https://desktop.github.com)) ad do the commit with Atom

**Reproduces how often:**

Every time, the problem also happens on `safe mode`.

### Versions

`atom --version`
Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

`git`
2.16.1

`OS`
Windows 10 1709

**Comment by 50Wliu** [comment] 2018-02-01 12:11
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #962. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2018-02-01 12:11 UTC
