### ISSUE TITLE
Can't create git branch for local repository

### ISSUE THREAD

**Issue by Elefant04** [atom/github#2408] opened 2019-12-08 14:03 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

I can't create a branch for a local repository

### Steps to Reproduce

1. Install atom new
2. Create in git tab a repo
3. Try to create a branch

**Expected behavior:**

A branch should be created

**Actual behavior:**

Nothing happens

**Reproduces how often:**

The whole time

### Versions

1.41.0

**Comment by smashwilson** [comment] 2020-02-29 16:08
Is there a stack trace in the dev console when you try?

**Comment by aguczam** [comment] 2020-04-08 20:29
NAME="Linux Mint"
VERSION="19.3 (Tricia)"
Atom version 1.45.0 x64

1.Start fresh atom
2.Setup github ( account token etc )
3.Github account on the internet is empty ( no projects there )
4. Atom panel shows Create Repository ( click )
5. Initialize git repository in directory ( directory path ) ( click +Init )
( the repository is created on github.com but is empty , config is proper when you try to push it to the server - right click on a Not a branch icon then push - error **fatal: invalid refspec 'no branch'** in dev console Uncaught (in promise) GitError: git push origin no branch --set-upstream in /home/youdontknow/github/myrepo exited with code 128
stdout: 
stderr: fatal: invalid refspec 'no branch'

    at new GitError (/usr/share/atom/resources/app/static/<embedded>:14:2475184)
    at Promise (/usr/share/atom/resources/app/static/<embedded>:14:2480346))

6. Create new file , write text, save as text.txt
7. On Git panel you will see [green plus] text.txt
8. Click GitHub and Publish On GitHub
9. Publish window pop up publish button - error - **Unable to determine the desired default branch from the repository**
10. on the bottom side of git panel no branch - click new branch -  nothing in the input box gives error about empty name anything else - no reaction no errors in dev window nothing
---------------------------------------------
to skip that bug
when in console in that repository directory:
terminal:
>git add test.txt
>git commit -m "some comment line"

Go back to Atom. The branch master should appear, ability to add new branches too ( once instead of master I got random stuff like asd but I was able to create master branch and remove asd by removing it from refs/heads dir. ) you can publish your project on github using Publish On GitHub button.

**Comment by thirstyice** [comment] 2020-04-13 01:29
Potentially a duplicate of #2418 ?

**Closed** 2021-04-12 11:21 UTC
Labels: more-information-needed
