### ISSUE TITLE
GitHub commit history is garbled when there is no Internet connection.

### ISSUE THREAD

**Issue by the-j0k3r** [atom/github#2089] opened 2019-04-19 10:19 UTC
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]? Yes
* Have you followed all applicable steps in the [debugging guide][debugging-guide]? Yes
* Have you checked the FAQs on the [message board][message-board] for common solutions? Yes
* Have you checked that your issue [isn't already filed][already-filed]? Yes, there are related to internet down but not same reports.

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

GitHub commit history is garbled when there is no Internet connection.

### Steps to Reproduce

This happened one day Internet was down and happened to boot machine at that time, so

Simulation: We need to simulate internet being unavailable at machine cold boot (this is important for some reason for consistent reproduction)

Not Simulated: Disabling the NIC and closing and reopening Atom has mixed results sometimes it does it sometimes it wont.

1. Disable your NIC or Unplug the cable 
2. Reboot, or boot the machine from cold.
3. Open Atom with any Git project associated.
4. You may need to fully close / reopen Git Tab as sometimes it loads nothing at all as if theres no Git project associated with that session even though there is.

**Expected behavior:**

[What did you expect to happen?]
No garbled text,.

**Actual behavior:**

[What actually happened instead?]
Garble Text

**Reproduces how often:**

[What percentage of the time does this happen?]
With simulation 100%
Without simulation varies

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

```
$ apm -v

apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.36.0
python
git 2.21.0.windows.1
visual studio

$ atom -v

Atom    : 1.36.0
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

Edit: 
github package version: 0.27.0

OS: Windows 10 Pro -1803 r17134.706
```
### Additional Information

Please include any additional information, configuration or data that might be necessary to reproduce the issue. Screenshots, if appropriate, are helpful as well.

If your issue involves a repository, and that repository is public, please include a link to it.

![Capture](https://user-images.githubusercontent.com/31389848/56419656-4b0b5e80-629b-11e9-892b-dc19746cacc1.PNG)

Any public repository will do, haven't tested with private repos.

**Comment by rsese** [comment] 2019-04-19 18:40
Thanks for the report @the-j0k3r :+1:

This is a duplicate of https://github.com/atom/github/issues/1528 and it was just fixed recently in https://github.com/atom/github/pull/2066 so the fix will be available in an upcoming release.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-04-19 18:40 UTC

**Comment by the-j0k3r** [comment] 2019-04-20 07:45
Thank you, glad its sorted and apologies for making a dupe ticket.

**Comment by rsese** [comment] 2019-04-22 16:46
np thanks for the heads up!
