### ISSUE TITLE
Switch git branch after commit, file is locked, and thus deleted

### ISSUE THREAD

**Issue by byronigoe** [atom/github#1418] opened 2018-04-24 12:43 UTC
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]? Yes, it happens in Safe Mode
* Have you followed all applicable steps in the [debugging guide][debugging-guide]? Yes, it still happens
* Have you checked the FAQs on the [message board][message-board] for common solutions? Yes, nothing found
* Have you checked that your issue [isn't already filed][already-filed]? Yes, nothing found

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

After committing changes to a file, and switching branches, the file is locked and therefore disappears.

### Steps to Reproduce

1. Create a new directory (e.g. C:\code\temp)
2. Open that folder in Atom
3. Create a file (e.g. file.txt)
4. Initialize a git repository in that directory
5. Stage and Commit the file
6. Create a new branch (e.g. my-branch)
7. Modify the file
8. Stage and Commit the changes to the file
9. Switch to a different branch (e.g. master)

**Expected behavior:**

Atom should be able to checkout the branch chosen in step 9

**Actual behavior:**

The file is locked, and therefore a file permission issue prevents the checkout from succeeding, and the file is effectively deleted.

Console shows:
Uncaught (in promise) Error: EPERM: operation not permitted, stat 'C:\code\temp\file.txt'

**Reproduces how often:**

This happens every time.

### Versions

Atom    : 1.26.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

Windows 10 Pro 64-bit, Version 1709, OS Build 16299.371

### Additional Information

![atom-git-branch-error](https://user-images.githubusercontent.com/10134042/39187348-0e7265fc-479b-11e8-8703-9baa9aab49d9.gif)

Full video: https://youtu.be/X0Y9q3lVebE

**Comment by byronigoe** [comment] 2018-04-24 13:49
For absolute clarity, nothing else is touching the file. I even disabled my anti-virus.

**Comment by Brollof** [comment] 2018-04-24 13:53
Related behavior: when you want to checkout modified file (which is already opened in atom) you'll get **error: unable to create file \<filename\>: Permission denied** . After that operation modifying and saving this file in Atom will result in getting "Unable to save file: Permission denied" error. 

Closing Atom resolves issue with checking out modified file.

**Comment by rsese** [comment] 2018-04-25 00:07
Thanks for report everyone - we've been unable to reproduce so far but we're currently tracking this in https://github.com/atom/atom/issues/17013 so you can subscribe there if you'd like.  From #17013, it seems like this isn't an issue in Atom 1.24.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-04-25 00:07 UTC

**Comment by loratov** [comment] 2018-04-29 06:40
I've experienced the same on Windows, git simply just is not working. I did not have any issues on my mac. 

Atom version: 1.26.1 and 1.26.0
Windows: Windows 10 Pro, 64-bit, Version 1709 OS Build 16299.371
