### ISSUE TITLE
Failed to reload the github package stylesheets

### ISSUE THREAD

**Issue by kostrows** [atom/github#978] opened 2017-06-23 16:10 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [github](https://github.com/atom/github) package 0.3.3

### Stack Trace

Failed to reload the github package stylesheets

```
At error evaluating function `fade`: color.toHSL is not a function in /Applications/Atom.app/Contents/Resources/app/node_modules/github/styles/variables.less:4:63

LessError: error evaluating function `fade`: color.toHSL is not a function
  at /Applications/Atom.app/Contents/Resources/app/node_modules/github/styles/variables.less:4:63
```

### Commands

```
 16x -2:17.9.0 core:backspace (input.hidden-input)
     -2:07.6.0 core:select-all (input.hidden-input)
     -2:07.4.0 core:backspace (input.hidden-input)
     -2:03.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
codecademy-atom-ui 0.2.0 
codecademy-syntax-theme 1.1.2 
intentions 1.1.2 
linter 2.2.0 
linter-htmlhint 1.3.3 
linter-ui-default 1.6.2 
seti-ui 1.8.0 
```

**Comment by rsese** [comment] 2017-06-29 21:10
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by rsese** [comment] 2017-06-29 21:14
Ohhh I noticed the themes you had installed so I just downloaded and enabled the `codecademy-atom-ui` theme and that immediately triggered the error.

I'll go ahead and close this but it may be that there is still a bug in Atom we'll need the `codecademy-atom-ui` maintainers to help track that down. You can file this issue on their [repository](https://github.com/mikedisbrow/codecademy-atom-ui) so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

**Closed by rsese** 2017-06-29 21:14 UTC
Labels: more-information-needed, uncaught-exception

**Comment by Searge** [comment] 2018-02-03 21:05
+1

**Comment by motoservo** [comment] 2019-05-17 20:46
Has too much time elapsed to add a +1 here? This was my favorite theme but I'm getting a few errors on load. Pardon that there are a handful of Twilight themes, I just resolved an issue where Atom would launch with a blank window and the solution was to remove "twilight-syntax-theme". I was trying to view each twilight (there are quite a few) and after trial and error, I believe this is the one I'd been using for the last year, and prefer over the others. So, my guess is that something updated in a package or in Atom and now this theme is throwing errors.

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.5
**Thrown From**: [github](https://github.com/atom/github) package 0.28.1


### Stack Trace

Failed to reload the github package stylesheets

```
At variable @ui-hue is undefined in /Applications/Atom.app/Contents/Resources/app.asar/node_modules/one-dark-ui/styles/ui-variables-custom.less:36:16

LessError: variable @ui-hue is undefined
at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/one-dark-ui/styles/ui-variables-custom.less:36:16
```

### Commands

```
     -7:30.1.0 tabs:split-left (li.texteditor.tab.sortable.active.right-clicked)
     -0:02.7.0 textmate-clipboard:copy (atom-notification.error.icon.icon-flame.native-key-bindings.has-detail.has-close)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-path-intellisense 1.1.1 
atom-shortcuts 0.0.2 
busy-signal 2.0.1 
city-lights-syntax 1.1.8 
cursor-history 0.13.2 
dash 1.7.1 
emmet 2.4.3 
emmet-snippets-compatibility 1.0.6 
ex-mode 0.18.0 
file-icons 2.1.32 
gist-it 0.9.2 
git-menu 2.0.5 
git-time-machine 2.1.0 
highlight-selected 0.16.0 
Hydrogen 2.9.0 
inline-autocomplete-textmate 0.0.6 
intentions 1.1.5 
jquery-snippets 11.0.0 
language-awk 0.1.12 
language-blade 0.42.0 
language-vue 0.24.0 
laravel 0.7.1 
laravel-eloquent-snippets 2.0.0 
laravel-helper 0.3.0 
linter 2.3.0 
linter-csslint 2.0.6 
linter-htmlhint 1.6.1 
linter-js-standard 6.1.1 
linter-js-yaml 1.4.6 
linter-jsonlint 1.4.0 
linter-php 1.6.1 
linter-ruby 1.3.1 
linter-sass-lint 1.9.0 
linter-shellcheck 1.6.0 
linter-tidy 2.4.0 
linter-ui-default 1.7.1 
linter-xmllint 1.4.4 
lipsum 0.1.0 
minimap 4.29.9 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
nav-panel-plus 0.3.2 
open-this 0.5.0 
php-cs-fixer 4.1.1 
pinned-tabs 2.1.1 
platformio-ide-terminal 2.9.1 
rainbow-tabs 2.5.1 
split-diff 1.6.0 
stacked-tabs 0.1.3 
stash-tabs 0.1.0 
sundown-syntax 0.1.0 
textmate-clipboard 0.3.0 
todo-show 2.3.2 
twilight 0.3.0 
twilight-syntax 0.8.0 
twilight-syntax-theme 0.1.1 
twilight-textmate-syntax 0.1.19 
twilight-textmate-syntax-refined 1.4.0 
twilight-updated-syntax 0.5.5 
twilight-w-syntax 0.1.2 
twilightly-syntax 0.1.1 
vim-mode-plus 1.36.0 
vue-autocomplete 0.1.1 
```

**Comment by Arcanemagus** [comment] 2019-05-20 22:57
@motoservo As [previously stated](https://github.com/atom/github/issues/978#issuecomment-312110391) issues like this are caused by the third party themes and are _very_ unlikely to be a problem within Atom itself. Please follow the instructions there to contact the theme author so they can get this fixed for you or let us know the issue within Atom that needs fixing.
